
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-12-17T12:54:29+0000",
 "dirty": true,
 "error": null,
 "full-revisionid": "c13cd6e26cbc3a4021df7a61c00620c66805519e",
 "version": "1.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
