import Kratos

class ApplyComponentTableProcess(Kratos.Process):
    def __init__(self, arg0: Kratos.ModelPart, arg1: Kratos.Parameters) -> None: ...

class ApplyConstantHydrostaticPressureProcess(Kratos.Process):
    def __init__(self, arg0: Kratos.ModelPart, arg1: Kratos.Parameters) -> None: ...

class ApplyDoubleTableProcess(Kratos.Process):
    def __init__(self, arg0: Kratos.ModelPart, arg1: Kratos.Parameters) -> None: ...

class ApplyHydrostaticPressureTableProcess(Kratos.Process):
    def __init__(self, arg0: Kratos.ModelPart, arg1: Kratos.Parameters) -> None: ...

class BilinearCohesive2DLaw(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class BilinearCohesive3DLaw(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class ElasticCohesive2DLaw(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class ElasticCohesive3DLaw(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class ElastoPlasticModMohrCoulombCohesive2DLaw(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class ElastoPlasticModMohrCoulombCohesive3DLaw(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class ElastoPlasticMohrCoulombCohesive2DLaw(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class ElastoPlasticMohrCoulombCohesive3DLaw(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class ExponentialCohesive2DLaw(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class ExponentialCohesive3DLaw(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class FracturePropagation2DUtilities:
    def __init__(self) -> None: ...
    def CheckFracturePropagation(self, arg0: Kratos.Parameters, arg1: Kratos.ModelPart, arg2: bool) -> bool: ...
    def MappingModelParts(self, arg0: Kratos.Parameters, arg1: Kratos.ModelPart, arg2: Kratos.ModelPart, arg3: bool) -> None: ...

class FracturePropagation3DUtilities:
    def __init__(self) -> None: ...
    def CheckFracturePropagation(self, arg0: Kratos.Parameters, arg1: Kratos.ModelPart, arg2: bool) -> bool: ...
    def MappingModelParts(self, arg0: Kratos.Parameters, arg1: Kratos.ModelPart, arg2: Kratos.ModelPart, arg3: bool) -> None: ...

class HyperElasticSolid3DLaw(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class InitialStress2DUtilities:
    def __init__(self) -> None: ...
    def SaveInitialStresses(self, arg0: Kratos.Parameters, arg1: Kratos.ModelPart) -> None: ...
    def TransferInitialStresses(self, arg0: Kratos.ModelPart, arg1: Kratos.ModelPart, arg2: bool) -> None: ...

class InitialStress3DUtilities:
    def __init__(self) -> None: ...
    def SaveInitialStresses(self, arg0: Kratos.Parameters, arg1: Kratos.ModelPart) -> None: ...
    def TransferInitialStresses(self, arg0: Kratos.ModelPart, arg1: Kratos.ModelPart, arg2: bool) -> None: ...

class IsotropicDamageCohesive2DLaw(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class IsotropicDamageCohesive3DLaw(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class KratosPoromechanicsApplication(Kratos.KratosApplication):
    def __init__(self) -> None: ...

class LinearElasticPlaneStrainSolid2DLaw(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class LinearElasticPlaneStressSolid2DLaw(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class LinearElasticSolid3DLaw(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class ModifiedMisesNonlocalDamage3DLaw(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class ModifiedMisesNonlocalDamagePlaneStrain2DLaw(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class ModifiedMisesNonlocalDamagePlaneStress2DLaw(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class PeriodicInterfaceProcess(Kratos.Process):
    def __init__(self, arg0: Kratos.ModelPart, arg1: Kratos.Parameters) -> None: ...

class PoroExplicitCDScheme(Kratos.Scheme):
    def __init__(self) -> None: ...

class PoroExplicitVVScheme(Kratos.Scheme):
    def __init__(self) -> None: ...

class PoroNewmarkDynamicUPlScheme(Kratos.Scheme):
    def __init__(self, arg0: float, arg1: float, arg2: float, arg3: float) -> None: ...

class PoroNewmarkQuasistaticDampedUPlScheme(Kratos.Scheme):
    def __init__(self, arg0: float, arg1: float, arg2: float, arg3: float) -> None: ...

class PoroNewmarkQuasistaticUPlScheme(Kratos.Scheme):
    def __init__(self, arg0: float, arg1: float, arg2: float, arg3: float) -> None: ...

class PoromechanicsExplicitNonlocalStrategy(Kratos.ImplicitSolvingStrategy):
    def __init__(self, arg0: Kratos.ModelPart, arg1: Kratos.Scheme, arg2: Kratos.Parameters, arg3: bool, arg4: bool, arg5: bool) -> None: ...

class PoromechanicsExplicitStrategy(Kratos.ImplicitSolvingStrategy):
    def __init__(self, arg0: Kratos.ModelPart, arg1: Kratos.Scheme, arg2: Kratos.Parameters, arg3: bool, arg4: bool, arg5: bool) -> None: ...

class PoromechanicsFaceLoadControlModuleProcess(Kratos.Process):
    def __init__(self, arg0: Kratos.ModelPart, arg1: Kratos.Parameters) -> None: ...

class PoromechanicsNewtonRaphsonNonlocalStrategy(Kratos.ImplicitSolvingStrategy):
    def __init__(self, arg0: Kratos.ModelPart, arg1: Kratos.Scheme, arg2: Kratos.ConvergenceCriteria, arg3: Kratos.BuilderAndSolver, arg4: Kratos.Parameters, arg5: int, arg6: bool, arg7: bool, arg8: bool) -> None: ...

class PoromechanicsNewtonRaphsonStrategy(Kratos.ImplicitSolvingStrategy):
    def __init__(self, arg0: Kratos.ModelPart, arg1: Kratos.Scheme, arg2: Kratos.ConvergenceCriteria, arg3: Kratos.BuilderAndSolver, arg4: Kratos.Parameters, arg5: int, arg6: bool, arg7: bool, arg8: bool) -> None: ...

class PoromechanicsRammArcLengthNonlocalStrategy(Kratos.ImplicitSolvingStrategy):
    def __init__(self, arg0: Kratos.ModelPart, arg1: Kratos.Scheme, arg2: Kratos.ConvergenceCriteria, arg3: Kratos.BuilderAndSolver, arg4: Kratos.Parameters, arg5: int, arg6: bool, arg7: bool, arg8: bool) -> None: ...

class PoromechanicsRammArcLengthStrategy(Kratos.ImplicitSolvingStrategy):
    def __init__(self, arg0: Kratos.ModelPart, arg1: Kratos.Scheme, arg2: Kratos.ConvergenceCriteria, arg3: Kratos.BuilderAndSolver, arg4: Kratos.Parameters, arg5: int, arg6: bool, arg7: bool, arg8: bool) -> None: ...
    def UpdateLoads(self) -> None: ...

class SimoJuLocalDamage3DLaw(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SimoJuLocalDamagePlaneStrain2DLaw(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SimoJuLocalDamagePlaneStress2DLaw(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SimoJuNonlocalDamage3DLaw(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SimoJuNonlocalDamagePlaneStrain2DLaw(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SimoJuNonlocalDamagePlaneStress2DLaw(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...
