# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: com/hayatapps/pa/service/paservice_request_service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'com/hayatapps/pa/service/paservice_request_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from com.hayatapps.pa.model import paservice_request_pb2 as com_dot_hayatapps_dot_pa_dot_model_dot_paservice__request__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n8com/hayatapps/pa/service/paservice_request_service.proto\x12\x18\x63om.hayatapps.pa.service\x1a.com/hayatapps/pa/model/paservice_request.proto\"n\n\x12PAServiceRequestRq\x12\x45\n\x0eserviceRequest\x18\x01 \x01(\x0b\x32(.com.hayatapps.pa.model.PAServiceRequestH\x00\x88\x01\x01\x42\x11\n\x0f_serviceRequest\"n\n\x12PAServiceRequestRs\x12\x45\n\x0eserviceRequest\x18\x01 \x01(\x0b\x32(.com.hayatapps.pa.model.PAServiceRequestH\x00\x88\x01\x01\x42\x11\n\x0f_serviceRequest2\xfd\x03\n\x1bPAServiceRequestCRUDService\x12t\n\x16\x43reatePAServiceRequest\x12,.com.hayatapps.pa.service.PAServiceRequestRq\x1a,.com.hayatapps.pa.service.PAServiceRequestRs\x12x\n\x18RetrievePAServiceRequest\x12,.com.hayatapps.pa.service.PAServiceRequestRq\x1a,.com.hayatapps.pa.service.PAServiceRequestRs0\x01\x12v\n\x16UpdatePAServiceRequest\x12,.com.hayatapps.pa.service.PAServiceRequestRq\x1a,.com.hayatapps.pa.service.PAServiceRequestRs0\x01\x12v\n\x16\x44\x65letePAServiceRequest\x12,.com.hayatapps.pa.service.PAServiceRequestRq\x1a,.com.hayatapps.pa.service.PAServiceRequestRs0\x01\x42\x39\n\x18\x63om.hayatapps.pa.serviceB\x1bPAServiceRequestCRUDServiceP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'com.hayatapps.pa.service.paservice_request_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030com.hayatapps.pa.serviceB\033PAServiceRequestCRUDServiceP\001'
  _globals['_PASERVICEREQUESTRQ']._serialized_start=134
  _globals['_PASERVICEREQUESTRQ']._serialized_end=244
  _globals['_PASERVICEREQUESTRS']._serialized_start=246
  _globals['_PASERVICEREQUESTRS']._serialized_end=356
  _globals['_PASERVICEREQUESTCRUDSERVICE']._serialized_start=359
  _globals['_PASERVICEREQUESTCRUDSERVICE']._serialized_end=868
# @@protoc_insertion_point(module_scope)
