from setuptools import setup,find_packages

setup(
    name='tiktik',
    version='0.1.1',
    packages=find_packages(),
    install_requires=[

    ],
    entry_points={
    "console_scripts": [
        "tiktik_kokul=tiktik.main:kokul",
        "tiktik_appleornotnaive=tiktik.main:appleornotnaive",
        "tiktik_appleornotcandi=tiktik.main:appleornotcandi",
        "tiktik_candsunnyorrain=tiktik.main:candsunnyorrain",
        "tiktik_carpreferencesfinds=tiktik.main:carpreferencesfinds",
        "tiktik_dbscan=tiktik.main:dbscan",
        "tiktik_diabetes_logistic=tiktik.main:diabetes_logistic",
        "tiktik_enjoysportfinds=tiktik.main:enjoysportfinds",
        "tiktik_finds=tiktik.main:finds",
        "tiktik_heirarchialclust=tiktik.main:heirarchialclust",
        "tiktik_heirarkmeansexam=tiktik.main:heirarkmeansexam",
        "tiktik_diabeteshmm=tiktik.main:diabeteshmm",
        "tiktik_hmmrainy=tiktik.main:hmmrainy",
        "tiktik_id3=tiktik.main:id3",
        "tiktik_kmeanscluster=tiktik.main:kmeanscluster",
        "tiktik_knniris=tiktik.main:knniris",
        "tiktik_naiveposorneg=tiktik.main:naiveposorneg",
        "tiktik_naivetsampletext=tiktik.main:naivetsampletext",
        "tiktik_orangeorapple=tiktik.main:orangeorapple",
        "tiktik_naivespamornot=tiktik.main:naivespamornot",
        "tiktik_svmiris=tiktik.main:svmiris",
        "tiktik_backwardimage=tiktik.main:backwardimage",
        "tiktik_facedetection=tiktik.main:facedetection",
        "tiktik_supportvmiris=tiktik.main:SupportVMIris",
        "tiktik_candidateapple=tiktik.main:candidateapple",
        "tiktik_candidateweather=tiktik.main:candidateweather",
        "tiktik_findssport=tiktik.main:findssport",
        "tiktik_findcar=tiktik.main:findcar",
        "tiktik_productsel=tiktik.main:productsel",
        "tiktik_id3diabe=tiktik.main:id3diabe",
        "tiktik_id3appleororange=tiktik.main:id3appleororange",
        "tiktik_imageback=tiktik.main:imageback",
        "tiktik_naivespam=tiktik.main:naivespam",
        "tiktik_naivetext=tiktik.main:naivetext",
        "tiktik_naiveiris2d=tiktik.main:naiveiris2d",
        "tiktik_naivebayesiris3d=tiktik.main:naivebayesiris3d",
        "tiktik_svmcustomer=tiktik.main:svmcustomer",
        "tiktik_kmeanscustomer=tiktik.main:kmeanscustomer",
        "tiktik_kmeansexam3d=tiktik.main:kmeansexam3d",
        "tiktik_heirarchialexam2d=tiktik.main:heirarchialexam2d",
        "tiktik_kavya=tiktik.main:kavya",
    ],
},

)