
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-12-13T13:46:59+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "391713482a715cc6f92b178f05a172e9bb7beb45",
 "version": "1.4.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
