
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-12-14T19:41:54-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "693deaaa7a8b307e44d453dd2f45fc6d4013b970",
 "version": "2024.12.14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
