# coding: utf-8

# flake8: noqa
"""
    Wandelbots Nova API

    Interact with robots in an easy and intuitive way. 

    The version of the OpenAPI document: 2.0.0 beta
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from .abb_controller import AbbController
from .abb_controller_egm_server import AbbControllerEgmServer
from .add_trajectory_error import AddTrajectoryError
from .add_trajectory_error_data import AddTrajectoryErrorData
from .add_trajectory_request import AddTrajectoryRequest
from .add_trajectory_response import AddTrajectoryResponse
from .all_joint_positions_request import AllJointPositionsRequest
from .all_joint_positions_response import AllJointPositionsResponse
from .app import App
from .array_input import ArrayInput
from .array_input_array_inner import ArrayInputArrayInner
from .array_output import ArrayOutput
from .array_output_array_inner import ArrayOutputArrayInner
from .behavior import Behavior
from .blending_auto import BlendingAuto
from .blending_position import BlendingPosition
from .boolean_value import BooleanValue
from .box import Box
from .box2 import Box2
from .capsule import Capsule
from .capsule2 import Capsule2
from .capture import Capture
from .cell import Cell
from .code_with_arguments import CodeWithArguments
from .collider import Collider
from .collider_shape import ColliderShape
from .collision import Collision
from .collision2 import Collision2
from .collision_contact import CollisionContact
from .collision_motion_group import CollisionMotionGroup
from .collision_motion_group_assembly import CollisionMotionGroupAssembly
from .collision_scene import CollisionScene
from .collision_scene_assembly import CollisionSceneAssembly
from .comparator import Comparator
from .compound import Compound
from .container_environment_inner import ContainerEnvironmentInner
from .container_image import ContainerImage
from .container_image_secrets_inner import ContainerImageSecretsInner
from .container_storage import ContainerStorage
from .controller_capabilities import ControllerCapabilities
from .controller_instance import ControllerInstance
from .controller_instance_list import ControllerInstanceList
from .convex_hull import ConvexHull
from .convex_hull2 import ConvexHull2
from .coordinate_system import CoordinateSystem
from .coordinate_systems import CoordinateSystems
from .cubic_spline_parameter import CubicSplineParameter
from .cycle_time import CycleTime
from .cylinder import Cylinder
from .cylinder2 import Cylinder2
from .dh_parameter import DHParameter
from .direction import Direction
from .direction_jogging_request import DirectionJoggingRequest
from .error import Error
from .execute_trajectory_request import ExecuteTrajectoryRequest
from .execute_trajectory_response import ExecuteTrajectoryResponse
from .execution_result import ExecutionResult
from .external_joint_stream_datapoint import ExternalJointStreamDatapoint
from .external_joint_stream_datapoint_value import ExternalJointStreamDatapointValue
from .fanuc_controller import FanucController
from .feedback_collision import FeedbackCollision
from .feedback_joint_limit_exceeded import FeedbackJointLimitExceeded
from .feedback_out_of_workspace import FeedbackOutOfWorkspace
from .feedback_singularity import FeedbackSingularity
from .flag import Flag
from .float_value import FloatValue
from .force_vector import ForceVector
from .geometry import Geometry
from .get_mode_response import GetModeResponse
from .google_protobuf_any import GoogleProtobufAny
from .http_exception_response import HTTPExceptionResponse
from .http_validation_error import HTTPValidationError
from .io_boolean_value import IOBooleanValue
from .io_boolean_value2 import IOBooleanValue2
from .io_description import IODescription
from .io_description_min import IODescriptionMin
from .io_direction import IODirection
from .io_float_value import IOFloatValue
from .io_float_value2 import IOFloatValue2
from .io_integer_value import IOIntegerValue
from .io_integer_value2 import IOIntegerValue2
from .io_value import IOValue
from .io_value_type import IOValueType
from .ios import IOs
from .ios_ios_inner import IOsIosInner
from .image_credentials import ImageCredentials
from .inconsitent_trajectory_size import InconsitentTrajectorySize
from .inconsitent_trajectory_size_inconsistent_trajectory_size import InconsitentTrajectorySizeInconsistentTrajectorySize
from .info_service_capabilities import InfoServiceCapabilities
from .initialize_movement_request import InitializeMovementRequest
from .initialize_movement_response import InitializeMovementResponse
from .initialize_movement_response_init_response import InitializeMovementResponseInitResponse
from .integer_value import IntegerValue
from .invalid_dof import InvalidDof
from .invalid_dof_invalid_dof import InvalidDofInvalidDof
from .jogging_response import JoggingResponse
from .jogging_service_capabilities import JoggingServiceCapabilities
from .joint_jogging_request import JointJoggingRequest
from .joint_limit import JointLimit
from .joint_limit_exceeded import JointLimitExceeded
from .joint_name import JointName
from .joint_position_request import JointPositionRequest
from .joint_trajectory import JointTrajectory
from .joints import Joints
from .kinematic_service_capabilities import KinematicServiceCapabilities
from .kuka_controller import KukaController
from .kuka_controller_rsi_server import KukaControllerRsiServer
from .limit_settings import LimitSettings
from .limits_override import LimitsOverride
from .list_io_descriptions_response import ListIODescriptionsResponse
from .list_io_values_response import ListIOValuesResponse
from .list_payloads_response import ListPayloadsResponse
from .list_program_metadata_response import ListProgramMetadataResponse
from .list_recipe_metadata_response import ListRecipeMetadataResponse
from .list_response import ListResponse
from .list_tcps_response import ListTcpsResponse
from .list_trajectories_response import ListTrajectoriesResponse
from .manufacturer import Manufacturer
from .mode_change_response import ModeChangeResponse
from .motion_command import MotionCommand
from .motion_command_blending import MotionCommandBlending
from .motion_command_path import MotionCommandPath
from .motion_group_behavior_getter import MotionGroupBehaviorGetter
from .motion_group_info import MotionGroupInfo
from .motion_group_infos import MotionGroupInfos
from .motion_group_instance import MotionGroupInstance
from .motion_group_instance_list import MotionGroupInstanceList
from .motion_group_joints import MotionGroupJoints
from .motion_group_physical import MotionGroupPhysical
from .motion_group_specification import MotionGroupSpecification
from .motion_group_state import MotionGroupState
from .motion_group_state_joint_limit_reached import MotionGroupStateJointLimitReached
from .motion_vector import MotionVector
from .mounting import Mounting
from .move_to_trajectory_via_joint_ptp_response import MoveToTrajectoryViaJointPTPResponse
from .movement import Movement
from .movement_error import MovementError
from .movement_error_error import MovementErrorError
from .movement_movement import MovementMovement
from .movement_state_type import MovementStateType
from .nan_value import NanValue
from .nan_value_nan_value import NanValueNanValue
from .op_mode import OpMode
from .operation_mode import OperationMode
from .optimizer_setup import OptimizerSetup
from .orientation_type import OrientationType
from .path import Path
from .path_cartesian_ptp import PathCartesianPTP
from .path_circle import PathCircle
from .path_cubic_spline import PathCubicSpline
from .path_joint_ptp import PathJointPTP
from .path_line import PathLine
from .pause_movement_request import PauseMovementRequest
from .pause_movement_response import PauseMovementResponse
from .pause_movement_response_pause_response import PauseMovementResponsePauseResponse
from .pause_on_io import PauseOnIO
from .payload import Payload
from .plan_trajectory_failed_response import PlanTrajectoryFailedResponse
from .plan_trajectory_failed_response_error_feedback import PlanTrajectoryFailedResponseErrorFeedback
from .plan_trajectory_request import PlanTrajectoryRequest
from .plan_trajectory_response import PlanTrajectoryResponse
from .plan_trajectory_response_response import PlanTrajectoryResponseResponse
from .plane2 import Plane2
from .planner_pose import PlannerPose
from .planning_limits import PlanningLimits
from .planning_limits_limit_range import PlanningLimitsLimitRange
from .playback_speed_request import PlaybackSpeedRequest
from .playback_speed_response import PlaybackSpeedResponse
from .playback_speed_response_playback_speed_response import PlaybackSpeedResponsePlaybackSpeedResponse
from .point_cloud import PointCloud
from .pose import Pose
from .pose2 import Pose2
from .program_metadata import ProgramMetadata
from .program_run import ProgramRun
from .program_run_state import ProgramRunState
from .program_runner_reference import ProgramRunnerReference
from .pyjectory_datatypes_core_pose import PyjectoryDatatypesCorePose
from .pyjectory_datatypes_serializer_orientation import PyjectoryDatatypesSerializerOrientation
from .pyjectory_datatypes_serializer_pose import PyjectoryDatatypesSerializerPose
from .pyjectory_datatypes_serializer_position import PyjectoryDatatypesSerializerPosition
from .recipe_metadata import RecipeMetadata
from .rectangle import Rectangle
from .rectangle2 import Rectangle2
from .rectangular_capsule import RectangularCapsule
from .rectangular_capsule2 import RectangularCapsule2
from .release_channel import ReleaseChannel
from .request import Request
from .request1 import Request1
from .robot_controller import RobotController
from .robot_controller_configuration import RobotControllerConfiguration
from .robot_controller_state import RobotControllerState
from .robot_link_geometry import RobotLinkGeometry
from .robot_state import RobotState
from .robot_system_mode import RobotSystemMode
from .robot_tcp import RobotTcp
from .robot_tcps import RobotTcps
from .safety_configuration import SafetyConfiguration
from .safety_setup import SafetySetup
from .safety_setup_safety_settings import SafetySetupSafetySettings
from .safety_setup_safety_zone import SafetySetupSafetyZone
from .safety_state_type import SafetyStateType
from .safety_type import SafetyType
from .safety_zone import SafetyZone
from .safety_zone_limits import SafetyZoneLimits
from .service_status import ServiceStatus
from .service_status_phase import ServiceStatusPhase
from .service_status_severity import ServiceStatusSeverity
from .service_status_status import ServiceStatusStatus
from .set_io import SetIO
from .set_io_values_request_inner import SetIOValuesRequestInner
from .set_output_values_request_inner import SetOutputValuesRequestInner
from .settable_robot_system_mode import SettableRobotSystemMode
from .single_joint_limit import SingleJointLimit
from .singularity_type_enum import SingularityTypeEnum
from .sphere import Sphere
from .sphere2 import Sphere2
from .standstill import Standstill
from .standstill_reason import StandstillReason
from .standstill_standstill import StandstillStandstill
from .start_movement_request import StartMovementRequest
from .start_on_io import StartOnIO
from .status import Status
from .store import Store
from .tcp_pose import TcpPose
from .tcp_pose_request import TcpPoseRequest
from .tcp_required import TcpRequired
from .tool_geometry import ToolGeometry
from .torque_exceeded import TorqueExceeded
from .torque_exceeded_torque_exceeded import TorqueExceededTorqueExceeded
from .unit_type import UnitType
from .universalrobots_controller import UniversalrobotsController
from .update_nova_version_request import UpdateNovaVersionRequest
from .update_program_metadata_request import UpdateProgramMetadataRequest
from .update_recipe_metadata_request import UpdateRecipeMetadataRequest
from .validation_error import ValidationError
from .validation_error_loc_inner import ValidationErrorLocInner
from .version_number import VersionNumber
from .vertex import Vertex
from .virtual_controller import VirtualController
from .virtual_controller_types import VirtualControllerTypes
from .virtual_robot_configuration import VirtualRobotConfiguration
from .yaskawa_controller import YaskawaController

__all__ = [
    "AbbController", 
    "AbbControllerEgmServer", 
    "AddTrajectoryError", 
    "AddTrajectoryErrorData", 
    "AddTrajectoryRequest", 
    "AddTrajectoryResponse", 
    "AllJointPositionsRequest", 
    "AllJointPositionsResponse", 
    "App", 
    "ArrayInput", 
    "ArrayInputArrayInner", 
    "ArrayOutput", 
    "ArrayOutputArrayInner", 
    "Behavior", 
    "BlendingAuto", 
    "BlendingPosition", 
    "BooleanValue", 
    "Box", 
    "Box2", 
    "Capsule", 
    "Capsule2", 
    "Capture", 
    "Cell", 
    "CodeWithArguments", 
    "Collider", 
    "ColliderShape", 
    "Collision", 
    "Collision2", 
    "CollisionContact", 
    "CollisionMotionGroup", 
    "CollisionMotionGroupAssembly", 
    "CollisionScene", 
    "CollisionSceneAssembly", 
    "Comparator", 
    "Compound", 
    "ContainerEnvironmentInner", 
    "ContainerImage", 
    "ContainerImageSecretsInner", 
    "ContainerStorage", 
    "ControllerCapabilities", 
    "ControllerInstance", 
    "ControllerInstanceList", 
    "ConvexHull", 
    "ConvexHull2", 
    "CoordinateSystem", 
    "CoordinateSystems", 
    "CubicSplineParameter", 
    "CycleTime", 
    "Cylinder", 
    "Cylinder2", 
    "DHParameter", 
    "Direction", 
    "DirectionJoggingRequest", 
    "Error", 
    "ExecuteTrajectoryRequest", 
    "ExecuteTrajectoryResponse", 
    "ExecutionResult", 
    "ExternalJointStreamDatapoint", 
    "ExternalJointStreamDatapointValue", 
    "FanucController", 
    "FeedbackCollision", 
    "FeedbackJointLimitExceeded", 
    "FeedbackOutOfWorkspace", 
    "FeedbackSingularity", 
    "Flag", 
    "FloatValue", 
    "ForceVector", 
    "Geometry", 
    "GetModeResponse", 
    "GoogleProtobufAny", 
    "HTTPExceptionResponse", 
    "HTTPValidationError", 
    "IOBooleanValue", 
    "IOBooleanValue2", 
    "IODescription", 
    "IODescriptionMin", 
    "IODirection", 
    "IOFloatValue", 
    "IOFloatValue2", 
    "IOIntegerValue", 
    "IOIntegerValue2", 
    "IOValue", 
    "IOValueType", 
    "IOs", 
    "IOsIosInner", 
    "ImageCredentials", 
    "InconsitentTrajectorySize", 
    "InconsitentTrajectorySizeInconsistentTrajectorySize", 
    "InfoServiceCapabilities", 
    "InitializeMovementRequest", 
    "InitializeMovementResponse", 
    "InitializeMovementResponseInitResponse", 
    "IntegerValue", 
    "InvalidDof", 
    "InvalidDofInvalidDof", 
    "JoggingResponse", 
    "JoggingServiceCapabilities", 
    "JointJoggingRequest", 
    "JointLimit", 
    "JointLimitExceeded", 
    "JointName", 
    "JointPositionRequest", 
    "JointTrajectory", 
    "Joints", 
    "KinematicServiceCapabilities", 
    "KukaController", 
    "KukaControllerRsiServer", 
    "LimitSettings", 
    "LimitsOverride", 
    "ListIODescriptionsResponse", 
    "ListIOValuesResponse", 
    "ListPayloadsResponse", 
    "ListProgramMetadataResponse", 
    "ListRecipeMetadataResponse", 
    "ListResponse", 
    "ListTcpsResponse", 
    "ListTrajectoriesResponse", 
    "Manufacturer", 
    "ModeChangeResponse", 
    "MotionCommand", 
    "MotionCommandBlending", 
    "MotionCommandPath", 
    "MotionGroupBehaviorGetter", 
    "MotionGroupInfo", 
    "MotionGroupInfos", 
    "MotionGroupInstance", 
    "MotionGroupInstanceList", 
    "MotionGroupJoints", 
    "MotionGroupPhysical", 
    "MotionGroupSpecification", 
    "MotionGroupState", 
    "MotionGroupStateJointLimitReached", 
    "MotionVector", 
    "Mounting", 
    "MoveToTrajectoryViaJointPTPResponse", 
    "Movement", 
    "MovementError", 
    "MovementErrorError", 
    "MovementMovement", 
    "MovementStateType", 
    "NanValue", 
    "NanValueNanValue", 
    "OpMode", 
    "OperationMode", 
    "OptimizerSetup", 
    "OrientationType", 
    "Path", 
    "PathCartesianPTP", 
    "PathCircle", 
    "PathCubicSpline", 
    "PathJointPTP", 
    "PathLine", 
    "PauseMovementRequest", 
    "PauseMovementResponse", 
    "PauseMovementResponsePauseResponse", 
    "PauseOnIO", 
    "Payload", 
    "PlanTrajectoryFailedResponse", 
    "PlanTrajectoryFailedResponseErrorFeedback", 
    "PlanTrajectoryRequest", 
    "PlanTrajectoryResponse", 
    "PlanTrajectoryResponseResponse", 
    "Plane2", 
    "PlannerPose", 
    "PlanningLimits", 
    "PlanningLimitsLimitRange", 
    "PlaybackSpeedRequest", 
    "PlaybackSpeedResponse", 
    "PlaybackSpeedResponsePlaybackSpeedResponse", 
    "PointCloud", 
    "Pose", 
    "Pose2", 
    "ProgramMetadata", 
    "ProgramRun", 
    "ProgramRunState", 
    "ProgramRunnerReference", 
    "PyjectoryDatatypesCorePose", 
    "PyjectoryDatatypesSerializerOrientation", 
    "PyjectoryDatatypesSerializerPose", 
    "PyjectoryDatatypesSerializerPosition", 
    "RecipeMetadata", 
    "Rectangle", 
    "Rectangle2", 
    "RectangularCapsule", 
    "RectangularCapsule2", 
    "ReleaseChannel", 
    "Request", 
    "Request1", 
    "RobotController", 
    "RobotControllerConfiguration", 
    "RobotControllerState", 
    "RobotLinkGeometry", 
    "RobotState", 
    "RobotSystemMode", 
    "RobotTcp", 
    "RobotTcps", 
    "SafetyConfiguration", 
    "SafetySetup", 
    "SafetySetupSafetySettings", 
    "SafetySetupSafetyZone", 
    "SafetyStateType", 
    "SafetyType", 
    "SafetyZone", 
    "SafetyZoneLimits", 
    "ServiceStatus", 
    "ServiceStatusPhase", 
    "ServiceStatusSeverity", 
    "ServiceStatusStatus", 
    "SetIO", 
    "SetIOValuesRequestInner", 
    "SetOutputValuesRequestInner", 
    "SettableRobotSystemMode", 
    "SingleJointLimit", 
    "SingularityTypeEnum", 
    "Sphere", 
    "Sphere2", 
    "Standstill", 
    "StandstillReason", 
    "StandstillStandstill", 
    "StartMovementRequest", 
    "StartOnIO", 
    "Status", 
    "Store", 
    "TcpPose", 
    "TcpPoseRequest", 
    "TcpRequired", 
    "ToolGeometry", 
    "TorqueExceeded", 
    "TorqueExceededTorqueExceeded", 
    "UnitType", 
    "UniversalrobotsController", 
    "UpdateNovaVersionRequest", 
    "UpdateProgramMetadataRequest", 
    "UpdateRecipeMetadataRequest", 
    "ValidationError", 
    "ValidationErrorLocInner", 
    "VersionNumber", 
    "Vertex", 
    "VirtualController", 
    "VirtualControllerTypes", 
    "VirtualRobotConfiguration", 
    "YaskawaController"
]