import Kratos

class ApplyComponentTableProcessDam(Kratos.Process):
    def __init__(self, arg0: Kratos.ModelPart, arg1: Kratos.Parameters) -> None: ...

class BossakDisplacementSmoothingScheme(Kratos.Scheme):
    def __init__(self, arg0: float, arg1: float, arg2: float) -> None: ...

class ConstructionUtility:
    def __init__(self, arg0: Kratos.ModelPart, arg1: Kratos.ModelPart, arg2: Kratos.PiecewiseLinearTable, arg3: Kratos.Parameters) -> None: ...
    def ActiveHeatFluxAzenha(self, arg0: Kratos.Parameters) -> None: ...
    def ActiveHeatFluxNoorzai(self, arg0: Kratos.Parameters) -> None: ...
    def AfterOutputStep(self) -> None: ...
    def AssignTimeActivation(self, arg0: str, arg1: int, arg2: float, arg3: float) -> None: ...
    def CheckTemperature(self, arg0: Kratos.Parameters) -> None: ...
    def Initialize(self) -> None: ...
    def InitializeSolutionStep(self, arg0: str, arg1: str, arg2: str, arg3: str, arg4: bool, arg5: bool, arg6: int) -> None: ...
    def SearchingFluxes(self) -> None: ...

class DamAddedMassConditionProcess(Kratos.Process):
    def __init__(self, arg0: Kratos.ModelPart, arg1: Kratos.Parameters) -> None: ...

class DamAzenhaHeatFluxProcess(Kratos.Process):
    def __init__(self, arg0: Kratos.ModelPart, arg1: Kratos.Parameters) -> None: ...

class DamBofangConditionTemperatureProcess(Kratos.Process):
    def __init__(self, arg0: Kratos.ModelPart, arg1: Kratos.Parameters) -> None: ...

class DamChemoMechanicalAgingYoungProcess(Kratos.Process):
    def __init__(self, arg0: Kratos.ModelPart, arg1: Kratos.Parameters) -> None: ...

class DamFixTemperatureConditionProcess(Kratos.Process):
    def __init__(self, arg0: Kratos.ModelPart, arg1: Kratos.Parameters) -> None: ...

class DamGroutingReferenceTemperatureProcess(Kratos.Process):
    def __init__(self, arg0: Kratos.ModelPart, arg1: Kratos.Parameters) -> None: ...

class DamHydroConditionLoadProcess(Kratos.Process):
    def __init__(self, arg0: Kratos.ModelPart, arg1: Kratos.Parameters) -> None: ...

class DamInputTableNodalYoungModulusProcess(Kratos.Process):
    def __init__(self, arg0: Kratos.ModelPart, arg1: Kratos.PiecewiseLinearTable, arg2: Kratos.Parameters) -> None: ...

class DamNodalReferenceTemperatureProcess(Kratos.Process):
    def __init__(self, arg0: Kratos.ModelPart, arg1: Kratos.PiecewiseLinearTable, arg2: Kratos.Parameters) -> None: ...

class DamNodalYoungModulusProcess(Kratos.Process):
    def __init__(self, arg0: Kratos.ModelPart, arg1: Kratos.Parameters) -> None: ...

class DamNoorzaiHeatFluxProcess(Kratos.Process):
    def __init__(self, arg0: Kratos.ModelPart, arg1: Kratos.Parameters) -> None: ...

class DamPScheme(Kratos.Scheme):
    def __init__(self, arg0: float, arg1: float) -> None: ...

class DamRandomFieldsVariableProcess(Kratos.Process):
    def __init__(self, arg0: Kratos.ModelPart, arg1: Kratos.PiecewiseLinearTable, arg2: Kratos.Parameters) -> None: ...

class DamReservoirConstantTemperatureProcess(Kratos.Process):
    def __init__(self, arg0: Kratos.ModelPart, arg1: Kratos.Parameters) -> None: ...

class DamReservoirMonitoringTemperatureProcess(Kratos.Process):
    def __init__(self, arg0: Kratos.ModelPart, arg1: Kratos.Parameters) -> None: ...

class DamTSolAirHeatFluxProcess(Kratos.Process):
    def __init__(self, arg0: Kratos.ModelPart, arg1: Kratos.Parameters) -> None: ...

class DamTemperaturebyDeviceProcess(Kratos.Process):
    def __init__(self, arg0: Kratos.ModelPart, arg1: Kratos.Parameters) -> None: ...

class DamUPScheme(Kratos.Scheme):
    def __init__(self, arg0: float, arg1: float, arg2: float, arg3: float) -> None: ...

class DamUpliftCircularConditionLoadProcess(Kratos.Process):
    def __init__(self, arg0: Kratos.ModelPart, arg1: Kratos.ModelPart, arg2: Kratos.Parameters) -> None: ...

class DamUpliftConditionLoadProcess(Kratos.Process):
    def __init__(self, arg0: Kratos.ModelPart, arg1: Kratos.ModelPart, arg2: Kratos.Parameters) -> None: ...

class DamWestergaardConditionLoadProcess(Kratos.Process):
    def __init__(self, arg0: Kratos.ModelPart, arg1: Kratos.Parameters) -> None: ...

class GlobalJointStressUtility:
    def __init__(self, arg0: Kratos.ModelPart, arg1: Kratos.Parameters) -> None: ...
    def ComputingGlobalStress(self) -> None: ...

class IncrementalUpdateStaticDampedSmoothingScheme(Kratos.Scheme):
    def __init__(self, arg0: float, arg1: float) -> None: ...

class IncrementalUpdateStaticSmoothingScheme(Kratos.Scheme):
    def __init__(self) -> None: ...

class KratosDamApplication(Kratos.KratosApplication):
    def __init__(self) -> None: ...

class LinearElastic2DPlaneStrainNodal(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class LinearElastic2DPlaneStressNodal(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class LinearElastic3DLawNodal(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class MappingVariables2DUtilities:
    def __init__(self) -> None: ...
    def MappingMechanicalModelParts(self, arg0: Kratos.ModelPart, arg1: Kratos.ModelPart, arg2: bool, arg3: bool) -> None: ...
    def MappingThermalModelParts(self, arg0: Kratos.ModelPart, arg1: Kratos.ModelPart, arg2: bool, arg3: bool) -> None: ...

class MappingVariables3DUtilities:
    def __init__(self) -> None: ...
    def MappingMechanicalModelParts(self, arg0: Kratos.ModelPart, arg1: Kratos.ModelPart, arg2: bool, arg3: bool) -> None: ...
    def MappingThermalModelParts(self, arg0: Kratos.ModelPart, arg1: Kratos.ModelPart, arg2: bool, arg3: bool) -> None: ...

class StreamlinesOutput3DUtilities:
    def __init__(self) -> None: ...
    def ComputeOutputStep(self, arg0: Kratos.ModelPart, arg1: int) -> None: ...

class ThermalLinearElastic2DPlaneStrain(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class ThermalLinearElastic2DPlaneStrainNodal(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class ThermalLinearElastic2DPlaneStress(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class ThermalLinearElastic2DPlaneStressNodal(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class ThermalLinearElastic3DLaw(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class ThermalLinearElastic3DLawNodal(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class ThermalModifiedMisesNonlocalDamage3DLaw(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class ThermalModifiedMisesNonlocalDamagePlaneStrain2DLaw(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class ThermalModifiedMisesNonlocalDamagePlaneStress2DLaw(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class ThermalSimoJuLocalDamage3DLaw(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class ThermalSimoJuLocalDamagePlaneStrain2DLaw(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class ThermalSimoJuLocalDamagePlaneStress2DLaw(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class ThermalSimoJuNonlocalDamage3DLaw(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class ThermalSimoJuNonlocalDamagePlaneStrain2DLaw(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class ThermalSimoJuNonlocalDamagePlaneStress2DLaw(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class TransferSelfweightStressUtility:
    def __init__(self) -> None: ...
    def Transfer(self, arg0: Kratos.ModelPart, arg1: Kratos.ModelPart, arg2: int) -> None: ...
    def TransferInitialStress(self, arg0: Kratos.ModelPart, arg1: int) -> None: ...
