from .zz import DarkCode
from .zz import Dev
from .zz import Quotes
from .zz import Base64
from .zz import BlackBox
from .zz import Programmer_Languages
from .zz import Whois
from .zz import WormGpt
from .zz import ChatGpt
from .zz import MD5
from .zz import Marshel
from .zz import masklink
from .zz import SHA1
from .zz import SHA256
from .zz import service_port
from .zz import Portscan
from .zz import IP
from .zz import Domain
from .zz import wifi