from typing import ClassVar

class DataLocation:
    __members__: ClassVar[dict] = ...  # read-only
    Condition: ClassVar[DataLocation] = ...
    Element: ClassVar[DataLocation] = ...
    ModelPart: ClassVar[DataLocation] = ...
    NodeHistorical: ClassVar[DataLocation] = ...
    NodeNonHistorical: ClassVar[DataLocation] = ...
    ProcessInfo: ClassVar[DataLocation] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...
