from typing import Tuple

class ElementSocketServer:
    def __init__(self) -> None: ...

    def start(self, addr: str, lossless: bool) -> None: ...

    def wait_for_frame(self) -> Tuple[bytes, bytes, str, str]: ...
