# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import femtum_sdk.core.analysis_pb2 as analysis__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in analysis_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AnalysisStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FindOpticalSpectralAnalyserSweepResults = channel.unary_unary(
                '/Analysis.Analysis/FindOpticalSpectralAnalyserSweepResults',
                request_serializer=analysis__pb2.FindResultDataRequestDto.SerializeToString,
                response_deserializer=analysis__pb2.OpticalSpectralAnalyserSweepResultDtoArray.FromString,
                _registered_method=True)


class AnalysisServicer(object):
    """Missing associated documentation comment in .proto file."""

    def FindOpticalSpectralAnalyserSweepResults(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnalysisServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FindOpticalSpectralAnalyserSweepResults': grpc.unary_unary_rpc_method_handler(
                    servicer.FindOpticalSpectralAnalyserSweepResults,
                    request_deserializer=analysis__pb2.FindResultDataRequestDto.FromString,
                    response_serializer=analysis__pb2.OpticalSpectralAnalyserSweepResultDtoArray.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Analysis.Analysis', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Analysis.Analysis', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Analysis(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def FindOpticalSpectralAnalyserSweepResults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Analysis.Analysis/FindOpticalSpectralAnalyserSweepResults',
            analysis__pb2.FindResultDataRequestDto.SerializeToString,
            analysis__pb2.OpticalSpectralAnalyserSweepResultDtoArray.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
