import Kratos
from typing import overload

class KratosMetisApplication(Kratos.KratosApplication):
    def __init__(self) -> None: ...

class MetisDivideHeterogeneousInputInMemoryProcess(Kratos.Process):
    @overload
    def __init__(self, arg0: Kratos.IO, arg1: Kratos.ModelPartIO, arg2: Kratos.DataCommunicator) -> None: ...
    @overload
    def __init__(self, arg0: Kratos.IO, arg1: Kratos.ModelPartIO, arg2: Kratos.DataCommunicator, arg3: int) -> None: ...
    @overload
    def __init__(self, arg0: Kratos.IO, arg1: Kratos.ModelPartIO, arg2: Kratos.DataCommunicator, arg3: int, arg4: int) -> None: ...
    @overload
    def __init__(self, arg0: Kratos.IO, arg1: Kratos.ModelPartIO, arg2: Kratos.DataCommunicator, arg3: int, arg4: int, arg5: bool) -> None: ...
    @overload
    def __init__(self, arg0: Kratos.IO, arg1: Kratos.ModelPartIO, arg2: int) -> None: ...
    @overload
    def __init__(self, arg0: Kratos.IO, arg1: Kratos.ModelPartIO, arg2: int, arg3: int) -> None: ...
    @overload
    def __init__(self, arg0: Kratos.IO, arg1: Kratos.ModelPartIO, arg2: int, arg3: int, arg4: int) -> None: ...
    @overload
    def __init__(self, arg0: Kratos.IO, arg1: Kratos.ModelPartIO, arg2: int, arg3: int, arg4: int, arg5: bool) -> None: ...

class MetisDivideHeterogeneousInputProcess(Kratos.Process):
    @overload
    def __init__(self, arg0: Kratos.IO, arg1: int) -> None: ...
    @overload
    def __init__(self, arg0: Kratos.IO, arg1: int, arg2: int) -> None: ...
    @overload
    def __init__(self, arg0: Kratos.IO, arg1: int, arg2: int, arg3: int) -> None: ...
    @overload
    def __init__(self, arg0: Kratos.IO, arg1: int, arg2: int, arg3: int, arg4: bool) -> None: ...

class MetisDivideNodalInputToPartitionsProcess(Kratos.Process):
    @overload
    def __init__(self, arg0: Kratos.IO, arg1: int, arg2: int) -> None: ...
    @overload
    def __init__(self, arg0: Kratos.IO, arg1: int) -> None: ...

class MetisDivideSubModelPartsHeterogeneousInputProcess(Kratos.Process):
    @overload
    def __init__(self, arg0: Kratos.IO, arg1: Kratos.Parameters, arg2: int) -> None: ...
    @overload
    def __init__(self, arg0: Kratos.IO, arg1: Kratos.Parameters, arg2: int, arg3: int) -> None: ...
    @overload
    def __init__(self, arg0: Kratos.IO, arg1: Kratos.Parameters, arg2: int, arg3: int, arg4: int) -> None: ...
    @overload
    def __init__(self, arg0: Kratos.IO, arg1: Kratos.Parameters, arg2: int, arg3: int, arg4: int, arg5: bool) -> None: ...
