import Kratos
from typing import overload

@overload
def Mean(arg0: Kratos.ModelPart, arg1: Kratos.DoubleVariable) -> float: ...
@overload
def Mean(arg0: Kratos.ModelPart, arg1: Kratos.Array1DVariable3) -> Kratos.Array3: ...
@overload
def RootMeanSquare(arg0: Kratos.ModelPart, arg1: Kratos.DoubleVariable) -> float: ...
@overload
def RootMeanSquare(arg0: Kratos.ModelPart, arg1: Kratos.Array1DVariable3) -> Kratos.Array3: ...
@overload
def Sum(arg0: Kratos.ModelPart, arg1: Kratos.DoubleVariable) -> float: ...
@overload
def Sum(arg0: Kratos.ModelPart, arg1: Kratos.Array1DVariable3) -> Kratos.Array3: ...
@overload
def Variance(arg0: Kratos.ModelPart, arg1: Kratos.DoubleVariable) -> tuple[float, float]: ...
@overload
def Variance(arg0: Kratos.ModelPart, arg1: Kratos.Array1DVariable3) -> tuple[Kratos.Array3, Kratos.Array3]: ...
