REMAIN_NUM: int

def getAllCores(): ...
def getRemainCores(cores_used): ...
def setProcessAffinity(pid, cores) -> None: ...
def getProcessAffinity(pid): ...
def calculateAffinityMask(cores): ...
def getCurrentCore(): ...
