
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-12-15T11:30:46-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "7910df05e7e9bca6a92a6f81eff996fda1f13cc1",
 "version": "0.0.206"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
