VERSION_YEAR = 2024
VERSION_MONTH = int('12')
VERSION_DAY = int('16')
VERSION_HOUR = int('08')
VERSION_MINUTE = int('28')
MAJOR_VERSION = 1
MINOR_VERSION = 0
PATCH_VERSION = 202412160828
version_date = '2024/12/16 08:28'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
