
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-12-13T09:46:26+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "088c73f4f6137f9101b908a712bf3cdd1507e2a9",
 "version": "0.1.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
