#ifndef ROOT_RConfigOptions
#define ROOT_RConfigOptions

#define R__CONFIGUREOPTIONS   "Backtrace_INCLUDE_DIR=/usr/include CLANG_EXECUTABLE_VERSION=16 CLING_INCLUDE_DIRS=/root/cppyy-backend/cling/src/interpreter/cling/include CMAKE_CACHE_MAJOR_VERSION=3 CMAKE_CACHE_MINOR_VERSION=18 CMAKE_CACHE_PATCH_VERSION=4 DL_LIBRARY_PATH=/usr/lib64/libdl.so LIBCLANG_LIBRARY_VERSION=16 LLVM_INCLUDE_BENCHMARKS=OFF LLVM_INCLUDE_EXAMPLES=OFF LLVM_INCLUDE_RUNTIMES=ON LLVM_INCLUDE_TOOLS=ON LLVM_INCLUDE_UTILS=ON LLVM_VERSION_PRINTER_SHOW_HOST_TARGET_INFO=ON ZLIB_INCLUDE_DIR=/root/cppyy-backend/cling/src/builtins/zlib ZLIB_INCLUDE_DIRS=/root/cppyy-backend/cling/src/builtins/zlib ZLIB_LIBRARIES=ZLIB::ZLIB ZLIB_VERSION=1.2.8 ZLIB_VERSION_STRING=1.2.8 "
#define R__CONFIGUREFEATURES  "cxx17  builtin_clang builtin_llvm builtin_zlib shared"

#endif
