from .node import ConfigNode as ConfigNode
from .utils import remove_intent_of_text as remove_intent_of_text
from typing import Iterable

def set_title(title: str): ...
def set_doc(doc: str): ...
def set_discriminator(discriminator: str): ...
def add_multi_type_field(field_name: str, types: Iterable[type[ConfigNode]], discriminator: str | None = None, field_title: str = '', field_doc: str = ''): ...
def add_union_field(field_name: str, types: Iterable[type[ConfigNode]], discriminator: str | None = None, field_title: str = '', field_doc: str = ''): ...
