# coding: utf-8

# flake8: noqa
"""
    Text2Motion API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from text2motion_client_api.models.bone import Bone
from text2motion_client_api.models.feedback_request_body import FeedbackRequestBody
from text2motion_client_api.models.generate_request_body import GenerateRequestBody
from text2motion_client_api.models.generate_response_body import GenerateResponseBody
from text2motion_client_api.models.http_validation_error import HTTPValidationError
from text2motion_client_api.models.location_inner import LocationInner
from text2motion_client_api.models.skeleton import Skeleton
from text2motion_client_api.models.validation_error import ValidationError
