from .builder import Builder as Builder
from .organizer import Organizer as Organizer
from .pkginstaller import PackageInstaller as PackageInstaller

def _get_project_name(path: str) -> str: ...
def cli() -> None: ...
