#ifndef NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION "6.2.2406-25-g0bb738b2"
#define NETGEN_VERSION_MAJOR 6
#define NETGEN_VERSION_MINOR 2
#define NETGEN_VERSION_PATCH 2406
#define NETGEN_VERSION_TWEAK 25
#define NETGEN_VERSION_HASH "g0bb738b2"
#endif // NETGEN_VERSION_HPP_INCLUDED
