# Generated by Django 5.0.4 on 2024-06-10 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_secret_name_alter_secret_value"),
        ("cfgstore", "0001_new_table_configentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="CameraConfig",
            fields=[
                (
                    "configentry_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="cfgstore.configentry",
                    ),
                ),
                ("rtsp_url", models.CharField(max_length=200)),
            ],
            bases=("cfgstore.configentry",),
        ),
    ]
