import Kratos
from . import Historical as Historical, NonHistorical as NonHistorical

class TemporalMethod:
    def __init__(self, arg0: Kratos.ModelPart, arg1: int) -> None: ...
    def CalculateStatistics(self) -> None: ...
    def GetEchoLevel(self) -> int: ...
    def GetModelPart(self) -> Kratos.ModelPart: ...
    def GetTotalTime(self) -> float: ...
    def InitializeStatisticsMethod(self, arg0: float) -> None: ...
