import Kratos
from typing import overload

@overload
def RandomFillConditionVariable(arg0: Kratos.ModelPart, arg1: Kratos.DoubleVariable, arg2: float, arg3: float) -> None: ...
@overload
def RandomFillConditionVariable(arg0: Kratos.ModelPart, arg1: Kratos.Array1DVariable3, arg2: float, arg3: float) -> None: ...
@overload
def RandomFillElementVariable(arg0: Kratos.ModelPart, arg1: Kratos.DoubleVariable, arg2: float, arg3: float) -> None: ...
@overload
def RandomFillElementVariable(arg0: Kratos.ModelPart, arg1: Kratos.Array1DVariable3, arg2: float, arg3: float) -> None: ...
@overload
def RandomFillNodalHistoricalVariable(arg0: Kratos.ModelPart, arg1: Kratos.DoubleVariable, arg2: float, arg3: float, arg4: int) -> None: ...
@overload
def RandomFillNodalHistoricalVariable(arg0: Kratos.ModelPart, arg1: Kratos.Array1DVariable3, arg2: float, arg3: float, arg4: int) -> None: ...
@overload
def RandomFillNodalNonHistoricalVariable(arg0: Kratos.ModelPart, arg1: Kratos.DoubleVariable, arg2: float, arg3: float) -> None: ...
@overload
def RandomFillNodalNonHistoricalVariable(arg0: Kratos.ModelPart, arg1: Kratos.Array1DVariable3, arg2: float, arg3: float) -> None: ...
