
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-12-17T16:01:59+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "2ec0b772b15a278b758fdbcafaa2b9132ed2fc0e",
 "version": "2.9.5.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
