
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-12-17T16:39:48+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "7c62e0ca990662d57c0df906e6048ee5aa806a8e",
 "version": "1.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
