import Kratos
import KratosStatisticsApplication.TemporalMethods
from . import NormMethods as NormMethods, ValueMethods as ValueMethods

def Max(arg0: Kratos.ModelPart, arg1: str, arg2: int, arg3: Kratos.Parameters) -> list[KratosStatisticsApplication.TemporalMethods.TemporalMethod]: ...
def Mean(arg0: Kratos.ModelPart, arg1: str, arg2: int, arg3: Kratos.Parameters) -> list[KratosStatisticsApplication.TemporalMethods.TemporalMethod]: ...
def Min(arg0: Kratos.ModelPart, arg1: str, arg2: int, arg3: Kratos.Parameters) -> list[KratosStatisticsApplication.TemporalMethods.TemporalMethod]: ...
def RootMeanSquare(arg0: Kratos.ModelPart, arg1: str, arg2: int, arg3: Kratos.Parameters) -> list[KratosStatisticsApplication.TemporalMethods.TemporalMethod]: ...
def Sum(arg0: Kratos.ModelPart, arg1: str, arg2: int, arg3: Kratos.Parameters) -> list[KratosStatisticsApplication.TemporalMethods.TemporalMethod]: ...
def Variance(arg0: Kratos.ModelPart, arg1: str, arg2: int, arg3: Kratos.Parameters) -> list[KratosStatisticsApplication.TemporalMethods.TemporalMethod]: ...
