from setuptools import setup, find_packages

setup(
    name="peslac",
    version="0.1.1",
    keywords=[
    "peslac",
    "api",
    "documents",
    "tools",
    "nodejs",
    "rag",
    "ai",
    "llm",
    "remote-file",
    "remote-file-processing",
    "document-processing",
    "file-processing",
    "ocr",
    "image-processing",
    "pdf-processing",
    "document-ocr",
    "image-ocr",
    "pdf-ocr",
    "document-processing",
    "image-processing",
    "pdf-processing",
    "pdf-splitter",
    "pdf-merger",
    "pdf-splitter",
    "pdf-merger",
    "pdf-splitter",
    "pdf-merger",
    "pdf-splitter",
    "pdf-merger",
    "pdf-splitter",
    "pdf-merger"
    ],
    packages=find_packages(),
    install_requires=[
        "requests",
        "requests-toolbelt",
    ],
    description="A Python package for the Peslac API",
    author="Jibril Kala",
    author_email="support@peslac.com",
    url="https://github.com/peslacai/peslac-python",
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    python_requires=">=3.7",
)
