import Kratos

def AddMissingDofs(arg0: Kratos.ModelPart) -> None: ...
def AddMissingDofsFromEntitiesList(arg0: Kratos.ModelPart, arg1) -> None: ...
def AddMissingVariables(arg0: Kratos.ModelPart) -> None: ...
def AddMissingVariablesFromEntitiesList(arg0: Kratos.ModelPart, arg1) -> None: ...
def CheckCompatibleConstitutiveLaws(arg0: Kratos.ModelPart) -> bool: ...
def CheckGeometricalPolynomialDegree(arg0: Kratos.ModelPart) -> int: ...
def DetermineFlagsUsed(arg0: Kratos.ModelPart) -> None: ...
def DetermineFramework(arg0: Kratos.ModelPart) -> str: ...
def DetermineIfCompatibleGeometries(arg0: Kratos.ModelPart) -> bool: ...
def DetermineIfRequiresTimeIntegration(arg0: Kratos.ModelPart) -> bool: ...
def DeterminePositiveDefiniteLHS(arg0: Kratos.ModelPart) -> bool: ...
def DetermineSymmetricLHS(arg0: Kratos.ModelPart) -> bool: ...
def DetermineTimeIntegration(arg0: Kratos.ModelPart) -> list[str]: ...
def GetDocumention(*args, **kwargs): ...
def GetDofsListFromConditionsSpecifications(arg0: Kratos.ModelPart) -> list[str]: ...
def GetDofsListFromElementsSpecifications(arg0: Kratos.ModelPart) -> list[str]: ...
def GetDofsListFromSpecifications(arg0: Kratos.ModelPart) -> list[str]: ...
