
from .main import kokul
from .main import appleornotnaive
from .main import appleornotcandi
from .main import candsunnyorrain
from .main import carpreferencesfinds
from .main import dbscan
from .main import diabetes_logistic
from .main import enjoysportfinds
from .main import finds
from .main import heirarchialclust
from .main import heirarkmeansexam
from .main import diabeteshmm
from .main import hmmrainy
from .main import id3
from .main import kmeanscluster
from .main import knniris
from .main import naiveposorneg
from .main import naivetsampletext
from .main import orangeorapple
from .main import naivespamornot
from .main import svmiris
from .main import backwardimage
