"""add hidden flag to forcing conditions

Revision ID: a73209e4df83
Revises: 7c67fc371bc8
Create Date: 2024-04-13 11:47:10.639438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a73209e4df83'
down_revision: Union[str, None] = '7c67fc371bc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forcing_conditions', sa.Column('value_hidden', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forcing_conditions', 'value_hidden')
    # ### end Alembic commands ###
