import Kratos
from typing import Callable, overload

@overload
def GetNormMethod(arg0: Kratos.IntegerVariable, arg1: str) -> Callable[[int], float]: ...
@overload
def GetNormMethod(arg0: Kratos.DoubleVariable, arg1: str) -> Callable[[float], float]: ...
@overload
def GetNormMethod(arg0: Kratos.Array1DVariable3, arg1: str) -> Callable[[Kratos.Array3], float]: ...
@overload
def GetNormMethod(arg0: Kratos.VectorVariable, arg1: str) -> Callable[[Kratos.Vector], float]: ...
@overload
def GetNormMethod(arg0: Kratos.MatrixVariable, arg1: str) -> Callable[[Kratos.Matrix], float]: ...
@overload
def RaiseToPower(arg0: int, arg1: float) -> int: ...
@overload
def RaiseToPower(arg0: float, arg1: float) -> float: ...
@overload
def RaiseToPower(arg0: Kratos.Array3, arg1: float) -> Kratos.Array3: ...
@overload
def RaiseToPower(arg0: Kratos.Vector, arg1: float) -> Kratos.Vector: ...
@overload
def RaiseToPower(arg0: Kratos.Matrix, arg1: float) -> Kratos.Matrix: ...
