# This file was auto-generated by Fern from our API Definition.

import typing
from ...types.model_result_info import ModelResultInfo
from ...types.model_result_info_with_plot import ModelResultInfoWithPlot

ModelsExecuteWithFileResponse = typing.Union[ModelResultInfo, ModelResultInfoWithPlot]
