from dataclasses import dataclass

def print_md(md: str): ...

@dataclass
class UserSelect:
    options: list[str]
    title: str = ...
    desc: str = ...
    required: bool = ...
    choices = ...
    def __post_init__(self) -> None: ...
    def single_select(self) -> int: ...
    def multiple_select(self) -> list[int]: ...
    def __init__(self, options, title=..., desc=..., required=...) -> None: ...
