import Kratos
from . import MeshingUtilities as MeshingUtilities
from typing import overload

class BinBasedMeshTransfer2D:
    def __init__(self) -> None: ...
    def DirectScalarVarInterpolation(self, arg0: Kratos.ModelPart, arg1: Kratos.ModelPart, arg2: Kratos.DoubleVariable, arg3: Kratos.DoubleVariable, arg4: Kratos.BinBasedFastPointLocator2D) -> None: ...
    def DirectVectorialVarInterpolation(self, arg0: Kratos.ModelPart, arg1: Kratos.ModelPart, arg2: Kratos.Array1DVariable3, arg3: Kratos.Array1DVariable3, arg4: Kratos.BinBasedFastPointLocator2D) -> None: ...
    def MappingFromMovingMesh_ScalarVar(self, arg0: Kratos.ModelPart, arg1: Kratos.ModelPart, arg2: Kratos.DoubleVariable, arg3: Kratos.DoubleVariable, arg4: Kratos.BinBasedFastPointLocator2D) -> None: ...
    def MappingFromMovingMesh_VariableMeshes_ScalarVar(self, arg0: Kratos.ModelPart, arg1: Kratos.ModelPart, arg2: Kratos.DoubleVariable, arg3: Kratos.DoubleVariable, arg4: Kratos.BinBasedNodesInElementLocator2D) -> None: ...
    def MappingFromMovingMesh_VariableMeshes_VectorialVar(self, arg0: Kratos.ModelPart, arg1: Kratos.ModelPart, arg2: Kratos.Array1DVariable3, arg3: Kratos.Array1DVariable3, arg4: Kratos.BinBasedNodesInElementLocator2D) -> None: ...
    def MappingFromMovingMesh_VectorialVar(self, arg0: Kratos.ModelPart, arg1: Kratos.ModelPart, arg2: Kratos.Array1DVariable3, arg3: Kratos.Array1DVariable3, arg4: Kratos.BinBasedFastPointLocator2D) -> None: ...

class BinBasedMeshTransfer3D:
    def __init__(self) -> None: ...
    def DirectScalarVarInterpolation(self, arg0: Kratos.ModelPart, arg1: Kratos.ModelPart, arg2: Kratos.DoubleVariable, arg3: Kratos.DoubleVariable, arg4: Kratos.BinBasedFastPointLocator3D) -> None: ...
    def DirectVectorialVarInterpolation(self, arg0: Kratos.ModelPart, arg1: Kratos.ModelPart, arg2: Kratos.Array1DVariable3, arg3: Kratos.Array1DVariable3, arg4: Kratos.BinBasedFastPointLocator3D) -> None: ...
    def MappingFromMovingMesh_ScalarVar(self, arg0: Kratos.ModelPart, arg1: Kratos.ModelPart, arg2: Kratos.DoubleVariable, arg3: Kratos.DoubleVariable, arg4: Kratos.BinBasedFastPointLocator3D) -> None: ...
    def MappingFromMovingMesh_VariableMeshes_ScalarVar(self, arg0: Kratos.ModelPart, arg1: Kratos.ModelPart, arg2: Kratos.DoubleVariable, arg3: Kratos.DoubleVariable, arg4: Kratos.BinBasedNodesInElementLocator3D) -> None: ...
    def MappingFromMovingMesh_VariableMeshes_VectorialVar(self, arg0: Kratos.ModelPart, arg1: Kratos.ModelPart, arg2: Kratos.Array1DVariable3, arg3: Kratos.Array1DVariable3, arg4: Kratos.BinBasedNodesInElementLocator3D) -> None: ...
    def MappingFromMovingMesh_VectorialVar(self, arg0: Kratos.ModelPart, arg1: Kratos.ModelPart, arg2: Kratos.Array1DVariable3, arg3: Kratos.Array1DVariable3, arg4: Kratos.BinBasedFastPointLocator3D) -> None: ...

class ComputeHessianSolMetricProcess(Kratos.Process):
    @overload
    def __init__(self, arg0: Kratos.ModelPart, arg1: Kratos.Parameters) -> None: ...
    @overload
    def __init__(self, arg0: Kratos.ModelPart, arg1: Kratos.DoubleVariable) -> None: ...
    @overload
    def __init__(self, arg0: Kratos.ModelPart, arg1: Kratos.DoubleVariable, arg2: Kratos.Parameters) -> None: ...

class ComputeHessianSolMetricProcess2D(Kratos.Process):
    @overload
    def __init__(self, arg0: Kratos.ModelPart, arg1: Kratos.Parameters) -> None: ...
    @overload
    def __init__(self, arg0: Kratos.ModelPart, arg1: Kratos.DoubleVariable) -> None: ...
    @overload
    def __init__(self, arg0: Kratos.ModelPart, arg1: Kratos.DoubleVariable, arg2: Kratos.Parameters) -> None: ...

class ComputeHessianSolMetricProcess3D(Kratos.Process):
    @overload
    def __init__(self, arg0: Kratos.ModelPart, arg1: Kratos.Parameters) -> None: ...
    @overload
    def __init__(self, arg0: Kratos.ModelPart, arg1: Kratos.DoubleVariable) -> None: ...
    @overload
    def __init__(self, arg0: Kratos.ModelPart, arg1: Kratos.DoubleVariable, arg2: Kratos.Parameters) -> None: ...

class ComputeHessianSolMetricProcessComp2D(Kratos.Process):
    @overload
    def __init__(self, arg0: Kratos.ModelPart, arg1: Kratos.Parameters) -> None: ...
    @overload
    def __init__(self, arg0: Kratos.ModelPart, arg1: Kratos.DoubleVariable) -> None: ...
    @overload
    def __init__(self, arg0: Kratos.ModelPart, arg1: Kratos.DoubleVariable, arg2: Kratos.Parameters) -> None: ...

class ComputeHessianSolMetricProcessComp3D(Kratos.Process):
    @overload
    def __init__(self, arg0: Kratos.ModelPart, arg1: Kratos.Parameters) -> None: ...
    @overload
    def __init__(self, arg0: Kratos.ModelPart, arg1: Kratos.DoubleVariable) -> None: ...
    @overload
    def __init__(self, arg0: Kratos.ModelPart, arg1: Kratos.DoubleVariable, arg2: Kratos.Parameters) -> None: ...

class ComputeLevelSetSolMetricProcess2D(Kratos.Process):
    @overload
    def __init__(self, arg0: Kratos.ModelPart, arg1: Kratos.Array1DVariable3) -> None: ...
    @overload
    def __init__(self, arg0: Kratos.ModelPart, arg1: Kratos.Array1DVariable3, arg2: Kratos.Parameters) -> None: ...

class ComputeLevelSetSolMetricProcess3D(Kratos.Process):
    @overload
    def __init__(self, arg0: Kratos.ModelPart, arg1: Kratos.Array1DVariable3) -> None: ...
    @overload
    def __init__(self, arg0: Kratos.ModelPart, arg1: Kratos.Array1DVariable3, arg2: Kratos.Parameters) -> None: ...

class Cutting_Isosurface_Application:
    def __init__(self) -> None: ...
    def AddModelPartElements(self, arg0: Kratos.ModelPart, arg1: Kratos.ModelPart, arg2: int) -> None: ...
    def AddSkinConditions(self, arg0: Kratos.ModelPart, arg1: Kratos.ModelPart, arg2: int) -> None: ...
    def DeleteCutData(self, arg0: Kratos.ModelPart) -> None: ...
    def GenerateScalarVarCut(self, arg0: Kratos.ModelPart, arg1: Kratos.ModelPart, arg2: Kratos.DoubleVariable, arg3: float, arg4: int, arg5: float) -> None: ...
    def GenerateVectorialVarCut(self, arg0: Kratos.ModelPart, arg1: Kratos.ModelPart, arg2: Kratos.Array1DVariable3, arg3: float, arg4: int, arg5: float) -> None: ...
    def UpdateCutData(self, arg0: Kratos.ModelPart, arg1: Kratos.ModelPart) -> None: ...

class GradualVariableInterpolationUtility:
    def __init__(self, *args, **kwargs) -> None: ...
    def InitializeInterpolationAndConstraints(self, arg0: Kratos.ModelPart, arg1: list[str], arg2: float, arg3: int, arg4: bool) -> None: ...
    def UpdateSolutionStepVariables(self, arg0: list[str], arg1: float, arg2: float, arg3: bool) -> None: ...

class InternalVariablesInterpolationProcess(Kratos.Process):
    @overload
    def __init__(self, arg0: Kratos.ModelPart, arg1: Kratos.ModelPart) -> None: ...
    @overload
    def __init__(self, arg0: Kratos.ModelPart, arg1: Kratos.ModelPart, arg2: Kratos.Parameters) -> None: ...

class KratosMeshingApplication(Kratos.KratosApplication):
    def __init__(self) -> None: ...

class LinearToQuadraticTetrahedraMeshConverter:
    def __init__(self, arg0: Kratos.ModelPart) -> None: ...
    def LocalConvertLinearToQuadraticTetrahedraMesh(self, arg0: bool, arg1: bool) -> None: ...

class LocalRefinePrismMesh:
    def __init__(self, arg0: Kratos.ModelPart) -> None: ...
    def LocalRefineMesh(self, arg0: bool, arg1: bool) -> None: ...

class LocalRefineTetrahedraMesh:
    def __init__(self, arg0: Kratos.ModelPart) -> None: ...
    def LocalRefineMesh(self, arg0: bool, arg1: bool) -> None: ...

class LocalRefineTetrahedraMeshOnlyOnBoundaries:
    def __init__(self, arg0: Kratos.ModelPart) -> None: ...
    def LocalRefineMesh(self, arg0: bool, arg1: bool) -> None: ...

class LocalRefineTetrahedraMeshParallelToBoundaries:
    def __init__(self, arg0: Kratos.ModelPart) -> None: ...
    def LocalRefineMesh(self, arg0: bool, arg1: bool) -> None: ...

class LocalRefineTriangleMesh:
    def __init__(self, arg0: Kratos.ModelPart) -> None: ...
    def LocalRefineMesh(self, arg0: bool, arg1: bool) -> None: ...

class LocalRefineTriangleMeshConditions:
    def __init__(self, arg0: Kratos.ModelPart) -> None: ...
    def LocalRefineMesh(self, arg0: bool, arg1: bool) -> None: ...

class MeshTransfer2D:
    def __init__(self) -> None: ...
    def DirectModelPartInterpolation(self, arg0: Kratos.ModelPart, arg1: Kratos.ModelPart) -> None: ...
    def DirectScalarVarInterpolation(self, arg0: Kratos.ModelPart, arg1: Kratos.ModelPart, arg2: Kratos.DoubleVariable, arg3: Kratos.DoubleVariable) -> None: ...
    def DirectVectorialVarInterpolation(self, arg0: Kratos.ModelPart, arg1: Kratos.ModelPart, arg2: Kratos.Array1DVariable3, arg3: Kratos.Array1DVariable3) -> None: ...

class MeshTransfer3D:
    def __init__(self) -> None: ...
    def DirectModelPartInterpolation(self, arg0: Kratos.ModelPart, arg1: Kratos.ModelPart) -> None: ...
    def DirectScalarVarInterpolation(self, arg0: Kratos.ModelPart, arg1: Kratos.ModelPart, arg2: Kratos.DoubleVariable, arg3: Kratos.DoubleVariable) -> None: ...
    def DirectVectorialVarInterpolation(self, arg0: Kratos.ModelPart, arg1: Kratos.ModelPart, arg2: Kratos.Array1DVariable3, arg3: Kratos.Array1DVariable3) -> None: ...

class MetricErrorProcess2D(Kratos.Process):
    @overload
    def __init__(self, arg0: Kratos.ModelPart) -> None: ...
    @overload
    def __init__(self, arg0: Kratos.ModelPart, arg1: Kratos.Parameters) -> None: ...

class MetricErrorProcess3D(Kratos.Process):
    @overload
    def __init__(self, arg0: Kratos.ModelPart) -> None: ...
    @overload
    def __init__(self, arg0: Kratos.ModelPart, arg1: Kratos.Parameters) -> None: ...

class MetricFastInit2D(Kratos.Process):
    def __init__(self, arg0: Kratos.ModelPart) -> None: ...

class MetricFastInit3D(Kratos.Process):
    def __init__(self, arg0: Kratos.ModelPart) -> None: ...

class MmgIO2D(Kratos.IO):
    @overload
    def __init__(self, arg0: str) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: Kratos.Parameters) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: Kratos.Parameters, arg2: Kratos.Flags) -> None: ...
    def GetMmgVersion(self) -> str: ...

class MmgIO3D(Kratos.IO):
    @overload
    def __init__(self, arg0: str) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: Kratos.Parameters) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: Kratos.Parameters, arg2: Kratos.Flags) -> None: ...
    def GetMmgVersion(self) -> str: ...

class MmgIOS(Kratos.IO):
    @overload
    def __init__(self, arg0: str) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: Kratos.Parameters) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: Kratos.Parameters, arg2: Kratos.Flags) -> None: ...
    def GetMmgVersion(self) -> str: ...

class MmgProcess2D(Kratos.Process):
    @overload
    def __init__(self, arg0: Kratos.ModelPart) -> None: ...
    @overload
    def __init__(self, arg0: Kratos.ModelPart, arg1: Kratos.Parameters) -> None: ...
    def CleanSuperfluousNodes(self) -> None: ...
    def GetMmgVersion(self) -> str: ...
    def OutputMdpa(self) -> None: ...

class MmgProcess3D(Kratos.Process):
    @overload
    def __init__(self, arg0: Kratos.ModelPart) -> None: ...
    @overload
    def __init__(self, arg0: Kratos.ModelPart, arg1: Kratos.Parameters) -> None: ...
    def CleanSuperfluousNodes(self) -> None: ...
    def GetMmgVersion(self) -> str: ...
    def OutputMdpa(self) -> None: ...

class MmgProcess3DSurfaces(Kratos.Process):
    @overload
    def __init__(self, arg0: Kratos.ModelPart) -> None: ...
    @overload
    def __init__(self, arg0: Kratos.ModelPart, arg1: Kratos.Parameters) -> None: ...
    def CleanSuperfluousNodes(self) -> None: ...
    def GetMmgVersion(self) -> str: ...
    def OutputMdpa(self) -> None: ...

class MultiscaleRefiningProcess(Kratos.Process):
    @overload
    def __init__(self, arg0: Kratos.ModelPart, arg1: Kratos.ModelPart, arg2: Kratos.ModelPart) -> None: ...
    @overload
    def __init__(self, arg0: Kratos.ModelPart, arg1: Kratos.ModelPart, arg2: Kratos.ModelPart, arg3: Kratos.Parameters) -> None: ...
    def ExecuteCoarsening(self) -> None: ...
    def ExecuteRefinement(self) -> None: ...
    def FixRefinedInterface(self, arg0: Kratos.DoubleVariable, arg1: bool) -> None: ...
    def GetCoarseModelPart(self) -> Kratos.ModelPart: ...
    def GetRefinedModelPart(self) -> Kratos.ModelPart: ...
    def GetVisualizationModelPart(self) -> Kratos.ModelPart: ...
    def InitializeRefinedModelPart(self, arg0: Kratos.ModelPart) -> None: ...
    def InitializeVisualizationModelPart(self, arg0: Kratos.ModelPart) -> None: ...
    @overload
    def TransferLastStepToCoarseModelPart(self, arg0: Kratos.DoubleVariable) -> None: ...
    @overload
    def TransferLastStepToCoarseModelPart(self, arg0: Kratos.Array1DVariable3) -> None: ...
    @overload
    def TransferLastStepToCoarseModelPart(self, arg0: Kratos.Array1DVariable4) -> None: ...
    @overload
    def TransferLastStepToCoarseModelPart(self, arg0: Kratos.Array1DVariable6) -> None: ...
    @overload
    def TransferLastStepToCoarseModelPart(self, arg0: Kratos.Array1DVariable9) -> None: ...
    @overload
    def TransferSubstepToRefinedInterface(self, arg0: Kratos.DoubleVariable, arg1: float) -> None: ...
    @overload
    def TransferSubstepToRefinedInterface(self, arg0: Kratos.Array1DVariable3, arg1: float) -> None: ...
    @overload
    def TransferSubstepToRefinedInterface(self, arg0: Kratos.Array1DVariable4, arg1: float) -> None: ...
    @overload
    def TransferSubstepToRefinedInterface(self, arg0: Kratos.Array1DVariable6, arg1: float) -> None: ...
    @overload
    def TransferSubstepToRefinedInterface(self, arg0: Kratos.Array1DVariable9, arg1: float) -> None: ...

class NodalValuesInterpolationProcess2D(Kratos.Process):
    @overload
    def __init__(self, arg0: Kratos.ModelPart, arg1: Kratos.ModelPart) -> None: ...
    @overload
    def __init__(self, arg0: Kratos.ModelPart, arg1: Kratos.ModelPart, arg2: Kratos.Parameters) -> None: ...
    def Execute(self) -> None: ...

class NodalValuesInterpolationProcess3D(Kratos.Process):
    @overload
    def __init__(self, arg0: Kratos.ModelPart, arg1: Kratos.ModelPart) -> None: ...
    @overload
    def __init__(self, arg0: Kratos.ModelPart, arg1: Kratos.ModelPart, arg2: Kratos.Parameters) -> None: ...
    def Execute(self) -> None: ...

class TriGenDropletModeler:
    def __init__(self) -> None: ...
    @overload
    def ReGenerateMeshDroplet(self, arg0: str, arg1: str, arg2: Kratos.ModelPart, arg3: Kratos.NodeEraseProcess, arg4: bool, arg5: bool, arg6: float, arg7: float) -> None: ...
    @overload
    def ReGenerateMeshDroplet(self, arg0: Kratos.ModelPart, arg1: Kratos.Element, arg2: Kratos.Condition, arg3: Kratos.NodeEraseProcess, arg4: bool, arg5: bool, arg6: float, arg7: float) -> None: ...

class TriGenGLASSModeler:
    def __init__(self) -> None: ...
    @overload
    def ReGenerateMeshGlass(self, arg0: str, arg1: str, arg2: Kratos.ModelPart, arg3: Kratos.NodeEraseProcess, arg4: bool, arg5: bool, arg6: float, arg7: float) -> None: ...
    @overload
    def ReGenerateMeshGlass(self, arg0: Kratos.ModelPart, arg1: Kratos.Element, arg2: Kratos.Condition, arg3: Kratos.NodeEraseProcess, arg4: bool, arg5: bool, arg6: float, arg7: float) -> None: ...

class TriGenPFEMModeler:
    def __init__(self) -> None: ...
    @overload
    def ReGenerateMesh(self, arg0: str, arg1: str, arg2: Kratos.ModelPart, arg3: Kratos.NodeEraseProcess, arg4: bool, arg5: bool, arg6: float, arg7: float) -> None: ...
    @overload
    def ReGenerateMesh(self, arg0: Kratos.ModelPart, arg1: Kratos.Element, arg2: Kratos.Condition, arg3: Kratos.NodeEraseProcess, arg4: bool, arg5: bool, arg6: float, arg7: float) -> None: ...

class TriGenPFEMModelerVMS:
    def __init__(self) -> None: ...
    def ReGenerateMesh(self, arg0: Kratos.ModelPart, arg1: Kratos.Element, arg2: Kratos.Condition, arg3: Kratos.NodeEraseProcess, arg4: bool, arg5: bool, arg6: float, arg7: float) -> None: ...

class TriGenPFEMSegment:
    def __init__(self) -> None: ...
    def ReGenerateMesh(self, arg0: str, arg1: str, arg2: Kratos.ModelPart, arg3: Kratos.NodeEraseProcess, arg4: bool, arg5: bool, arg6: float, arg7: float) -> None: ...
