
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-12-16T10:53:43+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "cab97ff916e385609cf6650e27ef063e7373f7c2",
 "version": "1.4.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
