# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: com/hayatapps/pa/model/paaccount.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'com/hayatapps/pa/model/paaccount.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&com/hayatapps/pa/model/paaccount.proto\x12\x16\x63om.hayatapps.pa.model\"n\n\tPAAccount\x12\x11\n\taccountId\x18\x01 \x01(\x04\x12\x19\n\x0c\x61\x63\x63ountTitle\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x11\n\tcreatedAt\x18\x03 \x01(\r\x12\x0f\n\x07\x62\x61lance\x18\x04 \x01(\x01\x42\x0f\n\r_accountTitleB0\n\x16\x63om.hayatapps.pa.modelB\tPAAccountH\x01P\x01\x80\x01\x00\x88\x01\x00\x90\x01\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'com.hayatapps.pa.model.paaccount_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.hayatapps.pa.modelB\tPAAccountH\001P\001\200\001\000\210\001\000\220\001\000'
  _globals['_PAACCOUNT']._serialized_start=66
  _globals['_PAACCOUNT']._serialized_end=176
# @@protoc_insertion_point(module_scope)
