# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: com/hayatapps/pa/model/paservice_request.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'com/hayatapps/pa/model/paservice_request.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.com/hayatapps/pa/model/paservice_request.proto\x12\x16\x63om.hayatapps.pa.model\"\x12\n\x10PAServiceRequestB0\n\x16\x63om.hayatapps.pa.modelB\tPAServiceH\x01P\x01\x80\x01\x00\x88\x01\x00\x90\x01\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'com.hayatapps.pa.model.paservice_request_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.hayatapps.pa.modelB\tPAServiceH\001P\001\200\001\000\210\001\000\220\001\000'
  _globals['_PASERVICEREQUEST']._serialized_start=74
  _globals['_PASERVICEREQUEST']._serialized_end=92
# @@protoc_insertion_point(module_scope)
