# coding: utf-8

"""
    Computebench Service API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from do_sdk_platform.api.tools_api import ToolsApi


class TestToolsApi(unittest.TestCase):
    """ToolsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ToolsApi()

    def tearDown(self) -> None:
        pass

    def test_delete_tool_execution_controller_delete_tool_execution(self) -> None:
        """Test case for delete_tool_execution_controller_delete_tool_execution

        """
        pass

    def test_execute_tool_controller_execute_tool(self) -> None:
        """Test case for execute_tool_controller_execute_tool

        """
        pass

    def test_get_tool_execution_controller_get_tool_execution(self) -> None:
        """Test case for get_tool_execution_controller_get_tool_execution

        """
        pass

    def test_update_execution_status_controller_update_execution_status(self) -> None:
        """Test case for update_execution_status_controller_update_execution_status

        """
        pass


if __name__ == '__main__':
    unittest.main()
