import Kratos
import KratosStructuralMechanicsApplication

class AdvanceInTimeHighCycleFatigueProcess(Kratos.Process):
    def __init__(self, arg0: Kratos.ModelPart, arg1: Kratos.Parameters) -> None: ...

class AssociativePlasticDamageModel3DDruckerPrager(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class AssociativePlasticDamageModel3DModifiedMohrCoulomb(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class AssociativePlasticDamageModel3DRankine(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class AssociativePlasticDamageModel3DVonMises(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class DamageDPlusDMinusMasonry3DLaw(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class DamageDPlusDMinusPlaneStressMasonry2DLaw(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class ElasticPlaneStressUncoupledShear2DLaw(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class ElementDeactivationProcess(Kratos.Process):
    def __init__(self, arg0: Kratos.ModelPart, arg1: Kratos.Parameters) -> None: ...

class FiniteStrainIsotropicPlasticity3DDruckerPragerDruckerPrager(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class FiniteStrainIsotropicPlasticity3DDruckerPragerModifiedMohrCoulomb(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class FiniteStrainIsotropicPlasticity3DDruckerPragerTresca(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class FiniteStrainIsotropicPlasticity3DDruckerPragerVonMises(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class FiniteStrainIsotropicPlasticity3DModifiedMohrCoulombDruckerPrager(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class FiniteStrainIsotropicPlasticity3DModifiedMohrCoulombModifiedMohrCoulomb(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class FiniteStrainIsotropicPlasticity3DModifiedMohrCoulombTresca(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class FiniteStrainIsotropicPlasticity3DModifiedMohrCoulombVonMises(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class FiniteStrainIsotropicPlasticity3DTrescaDruckerPrager(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class FiniteStrainIsotropicPlasticity3DTrescaModifiedMohrCoulomb(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class FiniteStrainIsotropicPlasticity3DTrescaTresca(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class FiniteStrainIsotropicPlasticity3DTrescaVonMises(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class FiniteStrainIsotropicPlasticity3DVonMisesDruckerPrager(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class FiniteStrainIsotropicPlasticity3DVonMisesModifiedMohrCoulomb(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class FiniteStrainIsotropicPlasticity3DVonMisesTresca(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class FiniteStrainIsotropicPlasticity3DVonMisesVonMises(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class FiniteStrainIsotropicPlasticityFactory(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class FiniteStrainKinematicPlasticity3DDruckerPragerDruckerPrager(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class FiniteStrainKinematicPlasticity3DDruckerPragerModifiedMohrCoulomb(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class FiniteStrainKinematicPlasticity3DDruckerPragerTresca(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class FiniteStrainKinematicPlasticity3DDruckerPragerVonMises(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class FiniteStrainKinematicPlasticity3DModifiedMohrCoulombDruckerPrager(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class FiniteStrainKinematicPlasticity3DModifiedMohrCoulombModifiedMohrCoulomb(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class FiniteStrainKinematicPlasticity3DModifiedMohrCoulombTresca(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class FiniteStrainKinematicPlasticity3DModifiedMohrCoulombVonMises(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class FiniteStrainKinematicPlasticity3DTrescaDruckerPrager(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class FiniteStrainKinematicPlasticity3DTrescaModifiedMohrCoulomb(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class FiniteStrainKinematicPlasticity3DTrescaTresca(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class FiniteStrainKinematicPlasticity3DTrescaVonMises(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class FiniteStrainKinematicPlasticity3DVonMisesDruckerPrager(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class FiniteStrainKinematicPlasticity3DVonMisesModifiedMohrCoulomb(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class FiniteStrainKinematicPlasticity3DVonMisesTresca(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class FiniteStrainKinematicPlasticity3DVonMisesVonMises(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class GenericSmallStrainViscoplasticity3D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class HyperElastic3DLaw(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class HyperElasticIsotropicHenky1D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class HyperElasticIsotropicOgden1D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class HyperElasticPlaneStrain2DLaw(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class HyperElasticQuasiIncompressibleNeoHookean3DLaw(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class KirchhoffSaintVenant3DLaw(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class KirchhoffSaintVenantPlaneStrain2DLaw(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class KirchhoffSaintVenantPlaneStress2DLaw(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class KratosConstitutiveLawsApplication(Kratos.KratosApplication):
    def __init__(self) -> None: ...

class LinearElasticOrthotropic2DLaw(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class MultiLinearElastic1DLaw(KratosStructuralMechanicsApplication.TrussConstitutiveLaw):
    def __init__(self) -> None: ...

class MultiLinearIsotropicPlaneStress2D(KratosStructuralMechanicsApplication.LinearElasticPlaneStress2DLaw):
    def __init__(self) -> None: ...

class ParallelRuleOfMixturesLaw2D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class ParallelRuleOfMixturesLaw3D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class PlasticityIsotropicKinematicJ2Law(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SerialParallelRuleOfMixturesLaw(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SetAutomatedInitialDamageProcess(Kratos.Process):
    def __init__(self, arg0: Kratos.ModelPart, arg1: Kratos.Parameters) -> None: ...

class SmallStrainDplusDminusDamageDruckerPragerDruckerPrager3D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainDplusDminusDamageDruckerPragerModifiedMohrCoulomb3D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainDplusDminusDamageDruckerPragerMohrCoulomb2D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainDplusDminusDamageDruckerPragerMohrCoulomb3D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainDplusDminusDamageDruckerPragerRankine3D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainDplusDminusDamageDruckerPragerSimoJu3D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainDplusDminusDamageDruckerPragerTresca3D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainDplusDminusDamageDruckerPragerVonMises3D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainDplusDminusDamageModifiedMohrCoulombDruckerPrager3D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainDplusDminusDamageModifiedMohrCoulombModifiedMohrCoulomb3D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainDplusDminusDamageModifiedMohrCoulombRankine3D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainDplusDminusDamageModifiedMohrCoulombSimoJu3D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainDplusDminusDamageModifiedMohrCoulombTresca3D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainDplusDminusDamageModifiedMohrCoulombVonMises3D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainDplusDminusDamageMohrCoulombDruckerPrager2D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainDplusDminusDamageMohrCoulombDruckerPrager3D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainDplusDminusDamageMohrCoulombMohrCoulomb2D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainDplusDminusDamageMohrCoulombMohrCoulomb3D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainDplusDminusDamageMohrCoulombRankine2D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainDplusDminusDamageMohrCoulombRankine3D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainDplusDminusDamageMohrCoulombSimoJu2D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainDplusDminusDamageMohrCoulombSimoJu3D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainDplusDminusDamageMohrCoulombTresca2D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainDplusDminusDamageMohrCoulombTresca3D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainDplusDminusDamageMohrCoulombVonMises2D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainDplusDminusDamageMohrCoulombVonMises3D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainDplusDminusDamageRankineDruckerPrager3D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainDplusDminusDamageRankineModifiedMohrCoulomb3D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainDplusDminusDamageRankineMohrCoulomb2D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainDplusDminusDamageRankineMohrCoulomb3D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainDplusDminusDamageRankineRankine3D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainDplusDminusDamageRankineSimoJu3D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainDplusDminusDamageRankineTresca3D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainDplusDminusDamageRankineVonMises3D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainDplusDminusDamageSimoJuDruckerPrager3D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainDplusDminusDamageSimoJuModifiedMohrCoulomb3D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainDplusDminusDamageSimoJuMohrCoulomb2D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainDplusDminusDamageSimoJuMohrCoulomb3D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainDplusDminusDamageSimoJuRankine3D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainDplusDminusDamageSimoJuSimoJu3D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainDplusDminusDamageSimoJuTresca3D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainDplusDminusDamageSimoJuVonMises3D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainDplusDminusDamageTrescaDruckerPrager3D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainDplusDminusDamageTrescaModifiedMohrCoulomb3D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainDplusDminusDamageTrescaMohrCoulomb2D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainDplusDminusDamageTrescaMohrCoulomb3D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainDplusDminusDamageTrescaRankine3D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainDplusDminusDamageTrescaSimoJu3D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainDplusDminusDamageTrescaTresca3D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainDplusDminusDamageTrescaVonMises3D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainDplusDminusDamageVonMisesDruckerPrager3D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainDplusDminusDamageVonMisesModifiedMohrCoulomb3D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainDplusDminusDamageVonMisesMohrCoulomb2D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainDplusDminusDamageVonMisesMohrCoulomb3D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainDplusDminusDamageVonMisesRankine3D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainDplusDminusDamageVonMisesSimoJu3D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainDplusDminusDamageVonMisesTresca3D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainDplusDminusDamageVonMisesVonMises3D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainHighCycleFatigue3DLawDruckerPrager(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainHighCycleFatigue3DLawModifiedMohrCoulomb(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainHighCycleFatigue3DLawMohrCoulomb(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainHighCycleFatigue3DLawRankine(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainHighCycleFatigue3DLawSimoJu(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainHighCycleFatigue3DLawTresca(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainHighCycleFatigue3DLawVonMises(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainIsotropicDamage3DDruckerPrager(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainIsotropicDamage3DLaw(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainIsotropicDamage3DModifiedMohrCoulomb(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainIsotropicDamage3DMohrCoulomb(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainIsotropicDamage3DRankine(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainIsotropicDamage3DSimoJu(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainIsotropicDamage3DTresca(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainIsotropicDamage3DVonMises(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainIsotropicDamageFactory(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainIsotropicDamageImplex3DLaw(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainIsotropicDamagePlaneStrain2DLaw(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainIsotropicDamagePlaneStrainDruckerPrager(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainIsotropicDamagePlaneStrainModifiedMohrCoulomb(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainIsotropicDamagePlaneStrainMohrCoulomb(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainIsotropicDamagePlaneStrainRankine(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainIsotropicDamagePlaneStrainSimoJu(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainIsotropicDamagePlaneStrainTresca(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainIsotropicDamagePlaneStrainVonMises(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainIsotropicDamagePlaneStressDruckerPrager(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainIsotropicDamagePlaneStressModifiedMohrCoulomb(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainIsotropicDamagePlaneStressMohrCoulomb(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainIsotropicDamagePlaneStressRankine(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainIsotropicDamagePlaneStressSimoJu(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainIsotropicDamagePlaneStressTresca(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainIsotropicDamagePlaneStressVonMises(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainIsotropicDamageTractionOnly3DLaw(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainIsotropicDamageTractionOnlyImplex3DLaw(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainIsotropicPlasticity3DDruckerPragerDruckerPrager(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainIsotropicPlasticity3DDruckerPragerModifiedMohrCoulomb(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainIsotropicPlasticity3DDruckerPragerMohrCoulomb(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainIsotropicPlasticity3DDruckerPragerTresca(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainIsotropicPlasticity3DDruckerPragerVonMises(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainIsotropicPlasticity3DModifiedMohrCoulombDruckerPrager(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainIsotropicPlasticity3DModifiedMohrCoulombModifiedMohrCoulomb(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainIsotropicPlasticity3DModifiedMohrCoulombTresca(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainIsotropicPlasticity3DModifiedMohrCoulombVonMises(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainIsotropicPlasticity3DMohrCoulombDruckerPrager(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainIsotropicPlasticity3DMohrCoulombMohrCoulomb(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainIsotropicPlasticity3DMohrCoulombTresca(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainIsotropicPlasticity3DMohrCoulombVonMises(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainIsotropicPlasticity3DTrescaDruckerPrager(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainIsotropicPlasticity3DTrescaModifiedMohrCoulomb(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainIsotropicPlasticity3DTrescaMohrCoulomb(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainIsotropicPlasticity3DTrescaTresca(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainIsotropicPlasticity3DTrescaVonMises(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainIsotropicPlasticity3DVonMisesDruckerPrager(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainIsotropicPlasticity3DVonMisesModifiedMohrCoulomb(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainIsotropicPlasticity3DVonMisesMohrCoulomb(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainIsotropicPlasticity3DVonMisesTresca(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainIsotropicPlasticity3DVonMisesVonMises(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainIsotropicPlasticityFactory(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainIsotropicPlasticityPlaneStrainDruckerPragerDruckerPrager(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainIsotropicPlasticityPlaneStrainDruckerPragerModifiedMohrCoulomb(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainIsotropicPlasticityPlaneStrainDruckerPragerMohrCoulomb(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainIsotropicPlasticityPlaneStrainDruckerPragerTresca(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainIsotropicPlasticityPlaneStrainDruckerPragerVonMises(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainIsotropicPlasticityPlaneStrainModifiedMohrCoulombDruckerPrager(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainIsotropicPlasticityPlaneStrainModifiedMohrCoulombModifiedMohrCoulomb(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainIsotropicPlasticityPlaneStrainModifiedMohrCoulombTresca(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainIsotropicPlasticityPlaneStrainModifiedMohrCoulombVonMises(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainIsotropicPlasticityPlaneStrainMohrCoulombDruckerPrager(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainIsotropicPlasticityPlaneStrainMohrCoulombMohrCoulomb(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainIsotropicPlasticityPlaneStrainMohrCoulombTresca(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainIsotropicPlasticityPlaneStrainMohrCoulombVonMises(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainIsotropicPlasticityPlaneStrainTrescaDruckerPrager(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainIsotropicPlasticityPlaneStrainTrescaModifiedMohrCoulomb(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainIsotropicPlasticityPlaneStrainTrescaMohrCoulomb(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainIsotropicPlasticityPlaneStrainTrescaTresca(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainIsotropicPlasticityPlaneStrainTrescaVonMises(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainIsotropicPlasticityPlaneStrainVonMisesDruckerPrager(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainIsotropicPlasticityPlaneStrainVonMisesModifiedMohrCoulomb(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainIsotropicPlasticityPlaneStrainVonMisesMohrCoulomb(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainIsotropicPlasticityPlaneStrainVonMisesTresca(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainIsotropicPlasticityPlaneStrainVonMisesVonMises(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainJ2Plasticity3DLaw(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainJ2PlasticityPlaneStrain2DLaw(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainKinematicPlasticity3DDruckerPragerDruckerPrager(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainKinematicPlasticity3DDruckerPragerModifiedMohrCoulomb(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainKinematicPlasticity3DDruckerPragerMohrCoulomb(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainKinematicPlasticity3DDruckerPragerTresca(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainKinematicPlasticity3DDruckerPragerVonMises(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainKinematicPlasticity3DModifiedMohrCoulombDruckerPrager(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainKinematicPlasticity3DModifiedMohrCoulombModifiedMohrCoulomb(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainKinematicPlasticity3DModifiedMohrCoulombTresca(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainKinematicPlasticity3DModifiedMohrCoulombVonMises(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainKinematicPlasticity3DMohrCoulombDruckerPrager(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainKinematicPlasticity3DMohrCoulombMohrCoulomb(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainKinematicPlasticity3DMohrCoulombTresca(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainKinematicPlasticity3DMohrCoulombVonMises(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainKinematicPlasticity3DTrescaDruckerPrager(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainKinematicPlasticity3DTrescaModifiedMohrCoulomb(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainKinematicPlasticity3DTrescaMohrCoulomb(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainKinematicPlasticity3DTrescaTresca(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainKinematicPlasticity3DTrescaVonMises(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainKinematicPlasticity3DVonMisesDruckerPrager(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainKinematicPlasticity3DVonMisesModifiedMohrCoulomb(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainKinematicPlasticity3DVonMisesMohrCoulomb(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainKinematicPlasticity3DVonMisesTresca(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainKinematicPlasticity3DVonMisesVonMises(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainKinematicPlasticityFactory(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainKinematicPlasticityPlaneStrainDruckerPragerDruckerPrager(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainKinematicPlasticityPlaneStrainDruckerPragerModifiedMohrCoulomb(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainKinematicPlasticityPlaneStrainDruckerPragerTresca(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainKinematicPlasticityPlaneStrainDruckerPragerVonMises(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainKinematicPlasticityPlaneStrainModifiedMohrCoulombDruckerPrager(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainKinematicPlasticityPlaneStrainModifiedMohrCoulombModifiedMohrCoulomb(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainKinematicPlasticityPlaneStrainModifiedMohrCoulombTresca(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainKinematicPlasticityPlaneStrainModifiedMohrCoulombVonMises(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainKinematicPlasticityPlaneStrainTrescaDruckerPrager(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainKinematicPlasticityPlaneStrainTrescaModifiedMohrCoulomb(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainKinematicPlasticityPlaneStrainTrescaTresca(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainKinematicPlasticityPlaneStrainTrescaVonMises(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainKinematicPlasticityPlaneStrainVonMisesDruckerPrager(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainKinematicPlasticityPlaneStrainVonMisesModifiedMohrCoulomb(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainKinematicPlasticityPlaneStrainVonMisesTresca(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainKinematicPlasticityPlaneStrainVonMisesVonMises(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainOrthotropicDamageDruckerPrager2D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainOrthotropicDamageDruckerPrager3D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainOrthotropicDamageModifiedMohrCoulomb2D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainOrthotropicDamageModifiedMohrCoulomb3D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainOrthotropicDamageMohrCoulomb2D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainOrthotropicDamageMohrCoulomb3D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainOrthotropicDamageRankine2D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainOrthotropicDamageRankine3D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainOrthotropicDamageSimoJu2D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainOrthotropicDamageSimoJu3D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainOrthotropicDamageTresca2D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainOrthotropicDamageTresca3D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainOrthotropicDamageVonMises2D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainOrthotropicDamageVonMises3D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainPlasticDamageModel3DVonMisesVonMisesDruckerPrager(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainPlasticDamageModel3DVonMisesVonMisesVonMises(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainThermalIsotropicDamage3DDruckerPrager(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainThermalIsotropicDamage3DModifiedMohrCoulomb(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainThermalIsotropicDamage3DMohrCoulomb(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainThermalIsotropicDamage3DRankine(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainThermalIsotropicDamage3DSimoJu(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainThermalIsotropicDamage3DTresca(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainThermalIsotropicDamage3DVonMises(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainThermalIsotropicDamagePlaneStrainDruckerPrager(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainThermalIsotropicDamagePlaneStrainModifiedMohrCoulomb(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainThermalIsotropicDamagePlaneStrainMohrCoulomb(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainThermalIsotropicDamagePlaneStrainRankine(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainThermalIsotropicDamagePlaneStrainSimoJu(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainThermalIsotropicDamagePlaneStrainTresca(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainThermalIsotropicDamagePlaneStrainVonMises(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainThermalIsotropicDamagePlaneStressDruckerPrager(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainThermalIsotropicDamagePlaneStressModifiedMohrCoulomb(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainThermalIsotropicDamagePlaneStressMohrCoulomb(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainThermalIsotropicDamagePlaneStressRankine(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainThermalIsotropicDamagePlaneStressSimoJu(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class SmallStrainThermalIsotropicDamagePlaneStressTresca(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class ThermalElasticIsotropic3D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class ThermalLinearPlaneStrain(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class ThermalLinearPlaneStress(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class TractionSeparationLaw3D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class TrussPlasticityConstitutiveLaw(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class ViscousGeneralizedKelvin3D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class ViscousGeneralizedMaxwell3D(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...

class WrinklingLinear2DLaw(Kratos.ConstitutiveLaw):
    def __init__(self) -> None: ...
