import Kratos

class ComputeDEMFaceLoadUtility:
    def __init__(self) -> None: ...
    def CalculateDEMFaceLoads(self, arg0: Kratos.ModelPart, arg1: float, arg2: float) -> None: ...
    def ClearDEMFaceLoads(self, arg0: Kratos.ModelPart) -> None: ...

class ControlModuleFemDem2DUtilities:
    def __init__(self, arg0: Kratos.ModelPart, arg1: Kratos.ModelPart, arg2: Kratos.Parameters) -> None: ...
    def ExecuteFinalizeSolutionStep(self) -> None: ...
    def ExecuteInitialize(self) -> None: ...
    def ExecuteInitializeSolutionStep(self) -> None: ...

class ControlModuleFemDemUtilities:
    def __init__(self, arg0: Kratos.ModelPart, arg1: Kratos.ModelPart, arg2: Kratos.Parameters) -> None: ...
    def ExecuteFinalizeSolutionStep(self) -> None: ...
    def ExecuteInitialize(self) -> None: ...
    def ExecuteInitializeSolutionStep(self) -> None: ...

class ControlModuleProcess(Kratos.Process):
    def __init__(self, arg0: Kratos.ModelPart, arg1: Kratos.Parameters) -> None: ...

class DemStructuresCouplingUtilities:
    def __init__(self) -> None: ...
    def CheckProvidedProperties(self, arg0: Kratos.Properties) -> str: ...
    def ComputeSandProduction(self, arg0: Kratos.ModelPart, arg1: Kratos.ModelPart, arg2: float) -> float: ...
    def ComputeSandProductionWithDepthFirstSearch(self, arg0: Kratos.ModelPart, arg1: Kratos.ModelPart, arg2: float) -> None: ...
    def ComputeSandProductionWithDepthFirstSearchNonRecursiveImplementation(self, arg0: Kratos.ModelPart, arg1: Kratos.ModelPart, arg2: float) -> float: ...
    def ComputeTriaxialSandProduction(self, arg0: Kratos.ModelPart, arg1: Kratos.ModelPart, arg2: Kratos.ModelPart, arg3: float) -> None: ...
    def MarkBrokenSpheres(self, arg0: Kratos.ModelPart) -> None: ...
    def SmoothLoadTrasferredToFem(self, arg0: Kratos.ModelPart, arg1: float) -> None: ...
    def TransferStructuresSkinToDem(self, arg0: Kratos.ModelPart, arg1: Kratos.ModelPart, arg2: Kratos.Properties) -> None: ...

class EffectiveStressesCommunicatorUtility:
    def __init__(self, arg0: Kratos.ModelPart, arg1: Kratos.ModelPart) -> None: ...
    def CommunicateCurrentRadialEffectiveStressesToDemWalls(self) -> None: ...
    def CommunicateGivenRadialEffectiveStressesToDemWalls(self, arg0: Kratos.Matrix) -> None: ...
    def CopyWallCurrentEffectiveStressesToOldEffectiveStresses(self) -> None: ...
    def Initialize(self) -> None: ...

class InterpolateStructuralSolutionForDEM:
    def __init__(self) -> None: ...
    def InterpolateStructuralSolution(self, arg0: Kratos.ModelPart, arg1: float, arg2: float, arg3: float, arg4: float) -> None: ...
    def RestoreStructuralSolution(self, arg0: Kratos.ModelPart) -> None: ...
    def SaveStructuralSolution(self, arg0: Kratos.ModelPart) -> None: ...

class KratosDemStructuresCouplingApplication(Kratos.KratosApplication):
    def __init__(self) -> None: ...

class MultiaxialControlModuleFEMDEMGeneralized2DUtilities:
    def __init__(self, arg0: Kratos.ModelPart, arg1: Kratos.ModelPart, arg2: Kratos.Parameters) -> None: ...
    def ExecuteFinalizeSolutionStep(self) -> None: ...
    def ExecuteInitialize(self) -> None: ...
    def ExecuteInitializeSolutionStep(self) -> None: ...

class PermeabilityTensorCommunicatorUtility:
    def __init__(self, arg0: Kratos.ModelPart, arg1: Kratos.ModelPart) -> None: ...
    def Initialize(self) -> None: ...
    def TrasferUpdatedPermeabilityTensor(self) -> None: ...

class PorePressureCommunicatorUtility:
    def __init__(self, arg0: Kratos.ModelPart, arg1: Kratos.ModelPart) -> None: ...
    def ComputeForceOnParticlesDueToPorePressureGradient(self) -> None: ...
    def Initialize(self) -> None: ...

class PostProcessUtilities:
    def __init__(self, arg0: Kratos.ModelPart) -> None: ...
    def GetCurrentContinuumBonds(self, arg0: list) -> None: ...
    def GetInitialContinuumBonds(self, arg0: list) -> None: ...
    def GetStickyStatus(self, arg0: list) -> None: ...

class SandProductionUtilities:
    def __init__(self) -> None: ...
    def MarkSandProductionParticlesForErasing(self, arg0: Kratos.ModelPart) -> None: ...

class StressFailureCheckUtilities:
    def __init__(self, arg0: Kratos.ModelPart, arg1: Kratos.Parameters) -> None: ...
    def ExecuteFinalizeSolutionStep(self) -> None: ...
