
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-12-13T18:21:03+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "b132fca91f3e1b11b111f9b89f68a55e4b7605c6",
 "version": "1.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
