# This file was auto-generated by Fern from our API Definition.

import typing

DocumentType = typing.Union[
    typing.Literal["txt", "docx", "pptx", "xlsx", "pdf", "png", "jpg", "csv", "tsv", "json"], typing.Any
]
