# coding: utf-8

"""
    Text2Motion API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from text2motion_client_api.models.feedback_request_body import FeedbackRequestBody

class TestFeedbackRequestBody(unittest.TestCase):
    """FeedbackRequestBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FeedbackRequestBody:
        """Test FeedbackRequestBody
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FeedbackRequestBody`
        """
        model = FeedbackRequestBody()
        if include_optional:
            return FeedbackRequestBody(
                request_id = 'bf325375-e030-4fcc-aa00-917317c57477',
                rating = 1
            )
        else:
            return FeedbackRequestBody(
                request_id = 'bf325375-e030-4fcc-aa00-917317c57477',
                rating = 1,
        )
        """

    def testFeedbackRequestBody(self):
        """Test FeedbackRequestBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
