# coding: utf-8

"""
    Text2Motion API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from text2motion_client_api.models.generate_response_body import GenerateResponseBody

class TestGenerateResponseBody(unittest.TestCase):
    """GenerateResponseBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GenerateResponseBody:
        """Test GenerateResponseBody
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GenerateResponseBody`
        """
        model = GenerateResponseBody()
        if include_optional:
            return GenerateResponseBody(
                result = '',
                request_id = ''
            )
        else:
            return GenerateResponseBody(
        )
        """

    def testGenerateResponseBody(self):
        """Test GenerateResponseBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
