# This file was auto-generated by Fern from our API Definition.

import typing

from ....types.dto_responses_author_search_response_failed_search_response import (
    DtoResponsesAuthorSearchResponseFailedSearchResponse,
)
from ....types.dto_responses_author_search_response_search_response import (
    DtoResponsesAuthorSearchResponseSearchResponse,
)

AuthorsPostResponse = typing.Union[
    DtoResponsesAuthorSearchResponseSearchResponse, DtoResponsesAuthorSearchResponseFailedSearchResponse
]
