import Kratos

def InitializeAllEntities(arg0: Kratos.ModelPart) -> None: ...
def InitializeConditions(arg0: Kratos.ModelPart) -> None: ...
def InitializeElements(arg0: Kratos.ModelPart) -> None: ...
def InitializeMasterSlaveConstraints(arg0: Kratos.ModelPart) -> None: ...
