# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic.v1 as pydantic

from ..core.datetime_utils import serialize_datetime


class ValidateLinkTokenResponse(pydantic.BaseModel):
    valid: bool
    expires_at: int = pydantic.Field(alias="expiresAt")
    workspace_id: str = pydantic.Field(alias="workspaceId")
    customer_id: str = pydantic.Field(alias="customerId")
    external_billing_id: typing.Optional[str] = pydantic.Field(alias="externalBillingId", default=None)

    def json(self, **kwargs: typing.Any) -> str:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().json(**kwargs_with_defaults)

    def dict(self, **kwargs: typing.Any) -> typing.Dict[str, typing.Any]:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().dict(**kwargs_with_defaults)

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True
        json_encoders = {dt.datetime: serialize_datetime}
