# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class VerifyJwtResponseStatus(str, enum.Enum):
    VALID = "VALID"
    INVALID = "INVALID"

    def visit(self, valid: typing.Callable[[], T_Result], invalid: typing.Callable[[], T_Result]) -> T_Result:
        if self is VerifyJwtResponseStatus.VALID:
            return valid()
        if self is VerifyJwtResponseStatus.INVALID:
            return invalid()
