
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-12-13T15:55:33+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "798cf1a62a6eebae3d5e96b04e56b39864d1bbcb",
 "version": "3.1.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
